// RP IPA Flashcards — word list data
const WORDS_VERSION = '1.8';

// ─────────────────────────────────────────────────────────────────────────────
// 'meaning' fields are extracted from the textbook where provided.
// Blank meanings are accepted — not all entries carry glosses in the source.
const wordlistWords = [
  // ── A (pages 196–199) ────────────────────────────────────────────────────
  { word: 'abdomen', ipa: "ˈæbdəmən", meaning: "(onder)buik; belly" },
  { word: 'abhor', ipa: "əbˈhɔː", meaning: "verafschuwen" },
  { word: 'abolish', ipa: "əˈbɒlɪʃ", meaning: "afschaffen" },
  { word: 'absenteeism', ipa: "ˈæbsnˈtiːɪzm", meaning: "verzuim, afwezigheid" },
  { word: 'absolute', ipa: "ˈæbsəluːt", meaning: "certainly, definitely" },
  { word: 'absolutely', ipa: "ˈæbsəˈluːtli", meaning: "certainly, definitely" },
  { word: 'absolve', ipa: "əbˈzɒlv", meaning: "he was absolved from his promise" },
  { word: 'absurd',         ipa: "əbˈsɜːd" },
  { word: 'abusive', ipa: "əˈbjuːsɪv", meaning: "stop using abusive language" },
  { word: 'abysmal', ipa: "əˈbɪzml", meaning: "bottomless; extremely bad" },
  { word: 'abyss', ipa: "əˈbɪs", meaning: "afgrond" },
  { word: 'access', ipa: "ˈækses", meaning: "to have access to" },
  { word: 'accessible', ipa: "əkˈsesəbl", meaning: "toegankelijk" },
  { word: 'accomplice', ipa: "əˈkʌmplɪs", meaning: "medeplichtige" },
  { word: 'acid', ipa: "ˈæsɪd", meaning: "sulphuric acid (zwavelzuur)" },
  { word: 'acknowledge',    ipa: "əkˈnɒlɪdʒ" },
  { word: 'acquiesce', ipa: "ˈækwiˈes", meaning: "to acquiesce in a decision" },
  { word: 'acrobat',        ipa: "ˈækrəbæt" },
  { word: 'acrobatic',      ipa: "ˈækrəˈbætɪk" },
  { word: 'actual', ipa: "ˈæktʃuəl", meaning: "adj." },
  { word: 'actually', ipa: "ˈækʃəli", meaning: "adv." },
  { word: 'Adidas',         ipa: "ˈædədæs" },
  { word: 'admonish', ipa: "ədˈmɒnɪʃ", meaning: "vermanen" },
  { word: 'adult', ipa: "ˈædʌlt", meaning: "n/adj." },
  { word: 'adultery', ipa: "əˈdʌltəri", meaning: "overspel" },
  { word: 'advantage',      ipa: "ədˈvaːntɪdʒ" },
  { word: 'advantageous',   ipa: "ˈædvənˈteɪdʒəs" },
  { word: 'adversary', ipa: "ˈædvəsri", meaning: "tegenstander" },
  { word: 'adverse', ipa: "ˈædvɜːs", meaning: "adverse weather conditions" },
  { word: 'adversely',      ipa: "ˈædvɜːsli" },
  { word: 'advertise',      ipa: "ˈædvətaɪz" },
  { word: 'advertisement',  ipa: "ədˈvɜːtɪsmənt" },
  { word: 'advice', ipa: "ədˈvaɪs", meaning: "n" },
  { word: 'advise', ipa: "ədˈvaɪz", meaning: "v" },
  { word: 'aerial', ipa: "ˈeəriəl", meaning: "antenne" },
  { word: 'aerosol', ipa: "ˈeərəsɒl", meaning: "spuitbus" },
  { word: 'aesthetic', ipa: "iːsˈθetɪk", meaning: "esthetisch" },
  { word: 'aftermath', ipa: "ˈaːftəmaːθ", meaning: "nasleep" },
  { word: 'aged', ipa: "ˈeɪdʒɪd", meaning: "an aged man; the aged" },
  { word: 'agriculture',    ipa: "ˈæɡrɪkʌltʃə" },
  { word: 'aisle', ipa: "aɪl", meaning: "zijbeuk; gangpad in kerk" },
  { word: 'Aladdin',        ipa: "əˈlædɪn" },
  { word: 'alas',           ipa: "əˈlæs" },
  { word: 'albeit', ipa: "ɔːlˈbiːɪt", meaning: "although (literary)" },
  { word: 'album',          ipa: "ˈælbəm" },
  { word: 'alderman', ipa: "ˈɔːldəmən", meaning: "mayor and alderman" },
  { word: 'algebra',        ipa: "ˈældʒɪbrə" },
  { word: 'alibi',          ipa: "ˈæləbaɪ" },
  { word: 'alien', ipa: "ˈeɪljən", meaning: "vreemdeling" },
  { word: 'alimony', ipa: "ˈæləməni", meaning: "alimentatie" },
  { word: 'allegation', ipa: "ˈælɪˈgeɪʃn", meaning: "aantijging" },
  { word: 'allege', ipa: "əˈledʒ", meaning: "X was alleged to have said ..." },
  { word: 'allegiance', ipa: "əˈliːdʒəns", meaning: "allegiance to the Crown" },
  { word: 'almanac',        ipa: "ˈɔːlmənæk" },
  { word: 'almond', ipa: "ˈaːmənd", meaning: "amandel" },
  { word: 'almost',         ipa: "ˈɔːlməʊst" },
  { word: 'alternate', ipa: "ɔːlˈtɜːnɪt", meaning: "on alternate days" },
  { word: 'altitude',       ipa: "ˈæltɪtjuːd" },
  { word: 'aluminium',      ipa: "ˈæləˈmɪnjəm" },
  { word: 'amateur',        ipa: "ˈæmətə" },
  { word: 'ambiguity', ipa: "ˈæmbrɡjuːəti", meaning: "dubbelzinnigheid" },
  { word: 'ambiguous',      ipa: "æmˈbɪɡjuəs" },
  { word: 'amiable', ipa: "ˈeɪmjəbl", meaning: "beminnelijk" },
  { word: 'amicable', ipa: "ˈæmɪkəbl", meaning: "vriend(schapp)elijk, minnelijk" },
  { word: 'among',          ipa: "əˈmʌŋ" },
  { word: 'anaesthetic', ipa: "ˈænɪsˈθetɪk", meaning: "verdoving" },
  { word: 'anaesthetise', ipa: "æˈniːsθətaɪz", meaning: "verdoven, een verdoving geven" },
  { word: 'analogous',      ipa: "əˈnæləɡəs" },
  { word: 'analogy',        ipa: "əˈnælədʒi" },
  { word: 'analyse', ipa: "ˈænəlaɪz", meaning: "v" },
  { word: 'anarchy',        ipa: "ˈænəki" },
  { word: 'anatomical',     ipa: "ˈænəˈtɒmɪkl" },
  { word: 'anatomy',        ipa: "əˈnætəmi" },
  { word: 'animosity',      ipa: "ˈænəˈmɒsəti" },
  { word: 'ant',            ipa: "ænt" },
  { word: 'anticipate',     ipa: "ænˈtɪsəpeɪt" },
  { word: 'antipathy',      ipa: "ænˈtɪpəθi" },
  { word: 'antique',        ipa: "ænˈtiːk" },
  { word: 'anxiety',        ipa: "æŋˈzaɪəti" },
  { word: 'anxious',        ipa: "ˈæŋʃəs" },
  { word: 'aperitif',       ipa: "əˈperəˈtiːf" },
  { word: 'aperture', ipa: "ˈæpətʃuə", meaning: "(lens)opening" },
  { word: 'apologise', ipa: "əˈpɒlədʒaɪz", meaning: "v" },
  { word: 'apology', ipa: "əˈpɒlədʒi", meaning: "n" },
  { word: 'apostrophe',     ipa: "əˈpɒstrəfi" },
  { word: 'appalling', ipa: "əˈpɔːlɪŋ", meaning: "shocking" },
  { word: 'apparatus',      ipa: "æpəˈreɪtəs" },
  { word: 'appreciate', ipa: "əˈpriːʃieɪt", meaning: "also: to increase in value" },
  { word: 'apprentice', ipa: "əˈprentɪs", meaning: "leerjongen, leerling" },
  { word: 'apricot', ipa: "ˈeɪprɪkɒt", meaning: "abrikoos" },
  { word: 'apron', ipa: "ˈeɪprən", meaning: "schort" },
  { word: 'Arab', ipa: "ˈærəb", meaning: "n" },
  { word: 'Arabian', ipa: "əˈreɪbjən", meaning: "adj." },
  { word: 'Arabic', ipa: "ˈærəbɪk", meaning: "the language; Arabic numerals" },
  { word: 'arcade', ipa: "aːˈkeɪd", meaning: "amusement arcade" },
  { word: 'archaic',        ipa: "aːˈkeɪɪk" },
  { word: 'archipelago', ipa: "ˈaːkɪˈpeləɡəʊ", meaning: "(sea with) large group of islands" },
  { word: 'architect',      ipa: "ˈaːkɪtekt" },
  { word: 'archives',       ipa: "ˈaːkaɪvz" },
  { word: 'aristocracy',    ipa: "ˈærɪˈstɒkrəsi" },
  { word: 'aristocrat',     ipa: "ˈærɪstəkræt" },
  { word: 'arithmetic', ipa: "əˈrɪθmətɪk", meaning: "n" },
  { word: 'artifice', ipa: "ˈaːtɪfɪs", meaning: "kunstgreep, list" },
  { word: 'artificial', ipa: "ˈaːtɪˈfɪʃl", meaning: "kunstmatig" },
  { word: 'artisan', ipa: "ˈaːtɪˈzæn", meaning: "skilled workman" },
  { word: 'ascent', ipa: "əˈsent", meaning: "the ascent of Mount Everest" },
  { word: 'ascertain',      ipa: "ˈæsəˈteɪn" },
  { word: 'asphalt',        ipa: "ˈæsfælt" },
  { word: 'assassin', ipa: "əˈsæsɪn", meaning: "moordenaar" },
  { word: 'assassinate', ipa: "əˈsæsɪneɪt", meaning: "murder (esp. politicans)" },
  { word: 'assassination',  ipa: "əˈsæsɪˈneɪʃn" },
  { word: 'assume',         ipa: "əˈsjuːm" },
  { word: 'asthma',         ipa: "ˈæsmə" },
  { word: 'astonish',       ipa: "əˈstɒnɪʃ" },
  { word: 'astronomy',      ipa: "əˈstrɒnəmi" },
  { word: 'asylum', ipa: "əˈsaɪləm", meaning: "political asylum" },
  { word: 'atheist',        ipa: "ˈeɪθiɪst" },
  { word: 'athlete',        ipa: "ˈæθliːt" },
  { word: 'athletics',      ipa: "æθˈletɪks" },
  { word: 'atrocious', ipa: "əˈtrəʊʃəs", meaning: "gruwelijk" },
  { word: 'atrocity',       ipa: "əˈtrɒsəti" },
  { word: 'attorney', ipa: "əˈtɜːni", meaning: "Attorney General" },
  { word: 'audacious', ipa: "ɔːˈdeɪʃəs", meaning: "daring, bold" },
  { word: 'audacity',       ipa: "ɔːˈdæsəti" },
  { word: 'aural', ipa: "ˈɔːrəl", meaning: "an aural surgeon (oor-)" },
  { word: 'automaton', ipa: "ɔːˈtɒmətən", meaning: "robot" },
  { word: 'automobile',     ipa: "ɔːtəməbiːl" },
  { word: 'avalanche', ipa: "ˈævəlaːnʃ", meaning: "lawine" },
  { word: 'average',        ipa: "ˈævrɪdʒ" },
  { word: 'aviation', ipa: "ˈeɪviˈeɪʃn", meaning: "luchtvaart" },
  { word: 'azure',          ipa: "ˈæʒə" },
  // ── B (pages 200–201) ────────────────────────────────────────────────────
  { word: 'balcony',        ipa: "ˈbælkəni" },
  { word: 'bald', ipa: "bɔːld", meaning: "Charles the Bald" },
  { word: 'ballet',         ipa: "ˈbæleɪ" },
  { word: 'balm', ipa: "baːm", meaning: "balsem" },
  { word: 'banana',         ipa: "bəˈnaːnə" },
  { word: 'banish',         ipa: "ˈbænɪʃ" },
  { word: 'bankruptcy',     ipa: "ˈbæŋkrəpsi" },
  { word: 'banquet',        ipa: "ˈbæŋkwɪt" },
  { word: 'baptise',        ipa: "bæpˈtaɪz" },
  { word: 'banal',          ipa: "bəˈnaːl" },
  { word: 'basic',          ipa: "ˈbeɪsɪk" },
  { word: 'bastard',        ipa: "ˈbaːstəd" },
  { word: 'beau', ipa: "bəʊ", meaning: "girl's admirer" },
  { word: 'Beauchamp',      ipa: "ˈbiːtʃəm" },
  { word: 'Beaulieu',       ipa: "ˈbjuːli" },
  { word: 'belfry', ipa: "ˈbelfri", meaning: "klokkentoren" },
  { word: 'belligerent', ipa: "bɪˈlɪdʒərənt", meaning: "oorlogszuchtig" },
  { word: 'beloved', ipa: "bɪˈlʌvɪd", meaning: "his beloved (wife)" },
  { word: 'benevolent', ipa: "bɪˈnevələnt", meaning: "welwillend, weldadig" },
  { word: 'benign', ipa: "bɪˈnaɪn", meaning: "benign tumours (goedaardige gezwellen)" },
  { word: 'benignant', ipa: "bɪˈnɪɡnənt", meaning: "kind (esp. to inferiors)" },
  { word: 'beret',          ipa: "ˈbereɪ" },
  { word: 'bestow', ipa: "bɪˈstəʊ", meaning: "schenken, verlenen" },
  { word: 'bewilder',       ipa: "bɪˈwɪldə" },
  { word: 'bias', ipa: "ˈbaɪəs", meaning: "biased = prejudiced" },
  { word: 'bigoted', ipa: "ˈbɪɡətɪd", meaning: "intolerant, narrow-minded" },
  { word: 'biscuit',        ipa: "ˈbɪskɪt" },
  { word: 'bison',          ipa: "ˈbaɪsn" },
  { word: 'blancmange', ipa: "bləˈmɒnʒ", meaning: "soort gelantinepudding" },
  { word: 'blemish', ipa: "ˈblemɪʃ", meaning: "without blemish, faultless" },
  { word: 'blessed', ipa: "ˈblesɪd", meaning: "the Blessed Virgin" },
  { word: 'blouse',         ipa: "blaʊz" },
  { word: 'bold', ipa: "bəʊld", meaning: "Charles the Bold" },
  { word: 'bolster',        ipa: "ˈbəʊlstə" },
  { word: 'boot', ipa: "buːt", meaning: "also: football boots" },
  { word: 'bough', ipa: "baʊ", meaning: "the boughs of a tree" },
  { word: 'bourgeois',      ipa: "ˈbʊəʒwaː" },
  { word: 'bourgeoisie',    ipa: "ˈbʊəʒwaːˈziː" },
  { word: 'bowels', ipa: "ˈbaʊəlz", meaning: "intestines" },
  { word: 'branch',         ipa: "braːntʃ" },
  { word: 'breath', ipa: "breθ", meaning: "n" },
  { word: 'breathe', ipa: "briːð", meaning: "v" },
  { word: 'breeches', ipa: "ˈbrɪtʃɪz", meaning: "e.g. riding-breeches; rijbroek" },
  { word: 'brevity',        ipa: "ˈbrevəti" },
  { word: 'brochure',       ipa: "ˈbrəʊʃə" },
  { word: 'brothel', ipa: "ˈbrɒθəl", meaning: "bordeel" },
  { word: 'browse', ipa: "braʊz", meaning: "afgrazen; grasduinen" },
  { word: 'bruise', ipa: "bruːz", meaning: "buil; blauwe plek" },
  { word: 'budgerigar', ipa: "ˈbʌdʒərɪɡaː", meaning: "soort parkiet" },
  { word: 'buffet', ipa: "ˈbʊfeɪ", meaning: "n: food from counter" },
  { word: 'bulletin',       ipa: "ˈbʊlətɪn" },
  { word: 'bully', ipa: "ˈbʊli", meaning: "pesten, intimideren" },
  { word: 'buoyant', ipa: "ˈbjuərəʊ", meaning: "a buoyant disposition" },
  { word: 'bureau',         ipa: "ˈbjuərəʊ" },
  { word: 'businessman',    ipa: "ˈbɪznɪsmən" },
  // ── C (pages 202–205) ────────────────────────────────────────────────────
  { word: 'Caesar',         ipa: "ˈsiːzə" },
  { word: 'calamity',       ipa: "kəˈlæməti" },
  { word: 'camouflage',     ipa: "kəˈnæl" },
  { word: 'canal', ipa: "kəˈnæl", meaning: "the Canary Islands" },
  { word: 'canary',         ipa: "kəˈneəri" },
  { word: 'cancel', ipa: "ˈkænsl", meaning: "afzeggen, annuleren" },
  { word: 'cancer',         ipa: "ˈkænsə" },
  { word: 'candidate',      ipa: "ˈkændɪdət" },
  { word: 'canoe',          ipa: "kəˈnuː" },
  { word: 'capacious', ipa: "kəˈpeɪʃəs", meaning: "ruim" },
  { word: 'capitulate',     ipa: "kəˈpɪtjʊleɪt" },
  { word: 'caprice', ipa: "kəˈpriːs", meaning: "gril" },
  { word: 'capsize',        ipa: "kæpˈsaɪz" },
  { word: 'caricature',     ipa: "ˈkærɪkətʃʊə" },
  { word: 'carriage',       ipa: "ˈkærɪdʒ" },
  { word: 'cashier', ipa: "kæˈʃɪə", meaning: "n/v" },
  { word: 'cassette', ipa: "kəˈset", meaning: "(AmE cartridge)" },
  { word: 'catacombe',      ipa: "ˈkætəkuːm" },
  { word: 'catastrophe',    ipa: "kəˈtæstrəfi" },
  { word: 'catechism',      ipa: "ˈkætəkɪzm" },
  { word: 'caterpillar', ipa: "ˈkætəpɪlə", meaning: "rups" },
  { word: 'cathedral',      ipa: "kəˈθiːdrəl" },
  { word: 'catholic',       ipa: "ˈkæθlɪk" },
  { word: 'catholicism',    ipa: "kəˈθɒlɪsɪzm" },
  { word: 'cease', ipa: "siːs", meaning: "to stop" },
  { word: 'cello',          ipa: "ˈtʃeləʊ" },
  { word: 'Celtic', ipa: "ˈseltɪk", meaning: "football team" },
  { word: 'centenary', ipa: "senˈtiːnri", meaning: "n/adj., eeuwfeest, honderdjarig" },
  { word: 'centrifugal', ipa: "senˈtrɪfjʊɡl", meaning: "centrifugal force: middelpunt vliedend" },
  { word: 'ceremonious', ipa: "ˈserɪˈməʊnjəs", meaning: "vormelijk, ceremonieus" },
  { word: 'chalet', ipa: "ˈʃæleɪ", meaning: "id., vakantiehuisje" },
  { word: 'champagne',      ipa: "ʃæmˈpeɪn" },
  { word: 'chancellor',     ipa: "ˈtʃaːnslə" },
  { word: 'chandelier', ipa: "ˈʃændəˈlɪə", meaning: "kroonluchter" },
  { word: 'chaos',          ipa: "ˈkeɪɒs" },
  { word: 'charlatan',      ipa: "ˈʃæpərəʊn" },
  { word: 'chasm', ipa: "ˈkæzm", meaning: "kloof, afgrond" },
  { word: 'chaste', ipa: "ˈtʃæsi", meaning: "kuis" },
  { word: 'chastity',       ipa: "ˈtʃæstaɪz" },
  { word: 'chauffeur',      ipa: "ˈʃəʊfə" },
  { word: 'chauvinism',     ipa: "ˈʃəʊvɪnɪzm" },
  { word: 'chemist',        ipa: "ˈkemɪst" },
  { word: 'cherub', ipa: "ˈtʃerəb", meaning: "cherubijn, engel" },
  { word: 'chestnut', ipa: "ˈtʃesnʌt", meaning: "kastanje(kleurig)" },
  { word: 'chic',           ipa: "ʃiːk" },
  { word: 'chimpanzee',     ipa: "ˈtʃɪmpænˈziː" },
  { word: 'chisel', ipa: "ˈtʃɪzl", meaning: "beitel" },
  { word: 'chivalrous', ipa: "ˈʃɪvlrəs", meaning: "ridderlijk" },
  { word: 'chocolate',      ipa: "ˈtʃɒklɪt" },
  { word: 'choir', ipa: "ˈkwaɪə", meaning: "(kerk)koor" },
  { word: 'cholera',        ipa: "ˈkɒlərə" },
  { word: 'choose',         ipa: "tʃuːz" },
  { word: 'chorus', ipa: "ˈkɔːrəs", meaning: "sing in chorus" },
  { word: 'circuit',        ipa: "ˈsɜːkɪt" },
  { word: 'circumstance',   ipa: "ˈsɜːkəmstəns" },
  { word: 'citadel',        ipa: "ˈsɪtədl" },
  { word: 'clandestine', ipa: "klænˈdestɪn", meaning: "secret, illicit" },
  { word: 'client',         ipa: "ˈklaɪənt" },
  { word: 'coalesce', ipa: "ˈkəʊəˈles", meaning: "samensmelten" },
  { word: 'cocaine',        ipa: "kəˈkeɪn" },
  { word: 'coincidence', ipa: "kəʊˈmsədəns", meaning: "samenloop van omstandigheden" },
  { word: 'colonel',        ipa: "ˈkɜːnl" },
  { word: 'colony',         ipa: "ˈkɒləni" },
  { word: 'combatant',      ipa: "ˈkɒmbətənt" },
  { word: 'comfort',        ipa: "ˈkʌmfət" },
  { word: 'comfortable',    ipa: "ˈkʌmftəbl" },
  { word: 'commentary', ipa: "ˈkɒməntri", meaning: "a radio commentary" },
  { word: 'committee',      ipa: "kəˈmɪti" },
  { word: 'company',        ipa: "ˈkʌmpəni" },
  { word: 'compass',        ipa: "ˈkʌmpəs" },
  { word: 'composition',    ipa: "ˈkɒmpəˈzɪʃn" },
  { word: 'comrade',        ipa: "ˈkɒmrɪd" },
  { word: 'conceited', ipa: "kənˈsiːtɪd", meaning: "verwaand" },
  { word: 'concise', ipa: "kənˈsaɪs", meaning: "beknopt" },
  { word: 'concrete', ipa: "ˈkɒŋkriːt", meaning: "n/adj., beton; concreet" },
  { word: 'condolence', ipa: "kənˈdəʊləns", meaning: "condolences: condoléances" },
  { word: 'connoisseur',    ipa: "ˈkɒnəˈsɜː" },
  { word: 'conquer',        ipa: "ˈkɒŋkə" },
  { word: 'conquest',       ipa: "ˈkɒŋkwest" },
  { word: 'conspiracy', ipa: "kənˈspɪrəsi", meaning: "samenzwering" },
  { word: 'conspirator',    ipa: "kənˈspɪrətə" },
  { word: 'constituency',   ipa: "kənˈstɪtjuənsi" },
  { word: 'consummate', ipa: "kənˈsʌmɪt", meaning: "with consummate skill" },
  { word: 'contagious', ipa: "kənˈteɪdʒəs", meaning: "~ disease, laughter" },
  { word: 'controversial',  ipa: "ˈkɒntrəˈvɜːʃl" },
  { word: 'controversy',    ipa: "kənˈtrɒvəsi" },
  { word: 'corps', ipa: "kɔː", meaning: "the Peace Corps" },
  { word: 'corpse', ipa: "kɔːps", meaning: "dead body" },
  { word: 'cosmopolitan',   ipa: "ˈkɒzməˈpɒlɪtən" },
  { word: 'counterfeit', ipa: "ˈkaʊntəfɪt", meaning: "counterfeit money (vals)" },
  { word: 'courageous',     ipa: "kəˈreɪdʒəs" },
  { word: 'courteous', ipa: "ˈkɜːtjəs", meaning: "hoffelijk" },
  { word: 'courtesy', ipa: "ˈkɜːtəsi", meaning: "by courtesy of" },
  { word: 'covert', ipa: "ˈkʌvət", meaning: "bedekt, heimelijk (glance)" },
  // ── D (pages 206–208) ────────────────────────────────────────────────────
  { word: 'daft', ipa: "daːft", meaning: "dom, maf" },
  { word: 'dance',          ipa: "daːns" },
  { word: 'data', ipa: "ˈdeɪtə", meaning: "pl. of datum; occ. sg." },
  { word: 'dearth', ipa: "dɜːθ", meaning: "schaarste" },
  { word: 'debris', ipa: "ˈdebriː", meaning: "puin" },
  { word: 'debt',           ipa: "det" },
  { word: 'debut',          ipa: "ˈdeɪbjuː" },
  { word: 'decisive',       ipa: "dɪˈsaɪsɪv" },
  { word: 'decrepit', ipa: "dɪˈkrepɪt", meaning: "(old and) weak" },
  { word: 'definite',       ipa: "ˈdefɪnɪt" },
  { word: 'definitive',     ipa: "dɪˈfɪnɪtɪv" },
  { word: 'deity', ipa: "ˈdeɪəti", meaning: "Roman deities" },
  { word: 'deluge', ipa: "ˈdeljuːdʒ", meaning: "(zond)vloed" },
  { word: 'democracy',      ipa: "dɪˈmɒkrəsi" },
  { word: 'democrat',       ipa: "ˈdeməkræt" },
  { word: 'demolish', ipa: "dɪˈmɒlɪʃ", meaning: "slopen" },
  { word: 'demolition', ipa: "ˈdeməˈlɪʃn", meaning: "~ worker (= sloper)" },
  { word: 'denim', ipa: "ˈdenɪm", meaning: "id." },
  { word: 'depot', ipa: "ˈdepəʊ", meaning: "an arms depot" },
  { word: 'deputy', ipa: "ˈdepjʊti", meaning: "deputy chairman" },
  { word: 'derelict', ipa: "ˈderəlɪkt", meaning: "abandoned, disused" },
  { word: 'derision', ipa: "dɪˈrɪʒn", meaning: "ridicule" },
  { word: 'desecrate', ipa: "ˈdesəkreɪt", meaning: "ontheiligen" },
  { word: 'deserve',        ipa: "dɪˈzɜːv" },
  { word: 'design',         ipa: "dɪˈzaɪn" },
  { word: 'designate', ipa: "ˈdezɪɡneɪt", meaning: "mark clearly; appoint" },
  { word: 'desist', ipa: "dɪˈzɪst", meaning: "to desist from sth. (iets nalaten)" },
  { word: 'despise', ipa: "dɪˈspaɪz", meaning: "verachten" },
  { word: 'despotism',      ipa: "ˈdespətɪzm" },
  { word: 'desultory', ipa: "ˈdesɪltri", meaning: "~ reading: te hooi en te gras" },
  { word: 'detour', ipa: "ˈdiːtʊə", meaning: "omweg" },
  { word: 'device', ipa: "dɪˈvaɪs", meaning: "a labour-saving device" },
  { word: 'devise', ipa: "dɪˈvaɪz", meaning: "v, verzinnen, bedenken" },
  { word: 'devour', ipa: "dɪˈvaʊə", meaning: "verscheuren" },
  { word: 'devout', ipa: "dɪˈvaʊt", meaning: "vroom" },
  { word: 'diabetes',       ipa: "ˈdaɪəˈbiːtɪz" },
  { word: 'diabetic', ipa: "ˈdaɪəˈbetɪk", meaning: "n/adj." },
  { word: 'diagonal',       ipa: "daɪˈæɡənl" },
  { word: 'diameter',       ipa: "daɪˈæmətə" },
  { word: 'diaper', ipa: "ˈdaɪəpə", meaning: "AmE for nappy (luier)" },
  { word: 'diminutive', ipa: "dɪˈmɪnjətɪv", meaning: "very small" },
  { word: 'diplomacy',      ipa: "dɪˈpləʊməsi" },
  { word: 'diplomat',       ipa: "ˈdɪpləmæt" },
  { word: 'disciple',       ipa: "dɪˈsaɪpl" },
  { word: 'discipline',     ipa: "ˈdɪsəplɪn" },
  { word: 'disclose', ipa: "dɪsˈkləʊz", meaning: "to disclose a secret" },
  { word: 'discretion', ipa: "dɪˈskreʃn", meaning: "prudence; freedom to decide" },
  { word: 'dismay', ipa: "dɪsˈmeɪ", meaning: "ontzetting, verslagenheid" },
  { word: 'disparate', ipa: "ˈdɪspərət", meaning: "verscheiden" },
  { word: 'distinct',       ipa: "dɪˈstɪŋkt" },
  { word: 'docile', ipa: "ˈdəʊsaɪl", meaning: "volgzaam" },
  { word: 'dogged', ipa: "ˈdɒɡɪd", meaning: "obstinate, determined" },
  { word: 'donkey', ipa: "ˈdɒŋki", meaning: "ezel" },
  { word: 'dough', ipa: "dəʊ", meaning: "deeg; 'poen'" },
  { word: 'draught',        ipa: "draːft" },
  { word: 'dread',          ipa: "dred" },
  { word: 'drought', ipa: "draʊt", meaning: "droogte" },
  { word: 'dwarf',          ipa: "dwɔːf" },
  { word: 'dysentery',      ipa: "ˈdɪsntri" },
  // ── E (pages 208–209) ────────────────────────────────────────────────────
  { word: 'echelon', ipa: "ˈeʃəlɒn", meaning: "the higher echelons" },
  { word: 'economic',       ipa: "ˈiːkəˈnɒmɪk" },
  { word: 'ecstasy',        ipa: "ˈekstəsi" },
  { word: 'eligible',       ipa: "ˈelɪdʒəbl" },
  { word: 'elite',          ipa: "eɪˈliːt" },
  { word: 'elocution', ipa: "ˈeləˈkjuːʃn", meaning: "art of speaking well" },
  { word: 'emaciated', ipa: "ɪˈmeɪʃietɪd", meaning: "uitgemergeld" },
  { word: 'eminent',        ipa: "ˈemɪnənt" },
  { word: 'enamel', ipa: "ɪˈnæml", meaning: "glazuur, email" },
  { word: 'encore', ipa: "ˈɒŋkɔː", meaning: "'bis', toegift" },
  { word: 'endeavour', ipa: "ɪnˈdevə", meaning: "n/v, effort, attempt" },
  { word: 'enough',         ipa: "ɪˈnʌf" },
  { word: 'entrails', ipa: "ˈentreɪlz", meaning: "ingewanden" },
  { word: 'envelope', ipa: "ˈenvələʊp", meaning: "n" },
  { word: 'envisage',       ipa: "ɪnˈvɪzɪdʒ" },
  { word: 'ephemeral', ipa: "ɪˈfemərəl", meaning: "kortstondig" },
  { word: 'episode',        ipa: "ˈepɪsəʊd" },
  { word: 'epoch',          ipa: "ˈiːpɒk" },
  { word: 'erudite',        ipa: "ˈerudaɪt" },
  { word: 'erudition',      ipa: "ˈeruˈdɪʃn" },
  { word: 'eschew', ipa: "ɪsˈtʃuː", meaning: "formal avoid" },
  { word: 'espionage',      ipa: "ˈespɪənaːʒ" },
  { word: 'ethics', ipa: "ˈeθɪks", meaning: "ethiek" },
  { word: 'euphemism',      ipa: "ˈjuːfəmɪzm" },
  { word: 'evasive', ipa: "ɪˈveɪsɪv", meaning: "an evasive answer (ontwijkend)" },
  { word: 'evolution',      ipa: "ˈiːvəˈluːʃn" },
  { word: 'exaggerate',     ipa: "ɪɡˈzædʒəreɪt" },
  { word: 'exact',          ipa: "ɪɡˈzækt" },
  { word: 'exaltation', ipa: "ˈeɡzɔːlˈteɪʃn", meaning: "vervoering" },
  { word: 'examine',        ipa: "ɪɡˈzæmɪn" },
  { word: 'example',        ipa: "ɪɡˈzaːmpl" },
  { word: 'exchequer', ipa: "ɪksˈtʃekə", meaning: "Chancellor of the Exchequer" },
  { word: 'execute',        ipa: "ˈeksɪkjuːt" },
  { word: 'executive',      ipa: "ɪɡˈzekjətɪv" },
  { word: 'exercise', ipa: "ˈeksəsaɪz", meaning: "n/v" },
  { word: 'exert', ipa: "ɪɡˈzɜːt", meaning: "to exert one's influence" },
  { word: 'exhale', ipa: "eksˈheɪl", meaning: "uitademen" },
  { word: 'exit',           ipa: "ˈeksɪt" },
  { word: 'expert', ipa: "ˈekspɜːt", meaning: "n/adj., expert advice" },
  { word: 'extraordinary',  ipa: "ɪkˈstrɔːdnri" },
  { word: 'extremist',      ipa: "ɪkˈstriːmɪst" },
  { word: 'exultation', ipa: "ˈeɡzʌlˈteɪʃn", meaning: "verrukking" },
  // ── F (pages 210–211) ────────────────────────────────────────────────────
  { word: 'facade', ipa: "fəˈsaːd", meaning: "front of a building" },
  { word: 'Fahrenheit',     ipa: "ˈfærənhaɪt" },
  { word: 'falcon',         ipa: "ˈfɔːlkən" },
  { word: 'famine', ipa: "ˈfæmɪn", meaning: "(hongers)nood" },
  { word: 'fatigue', ipa: "fəˈtiːɡ", meaning: "metal fatigue" },
  { word: 'fault',          ipa: "fɔːlt" },
  { word: 'feasible', ipa: "ˈfiːzəbl", meaning: "uitvoerbaar" },
  { word: 'feign', ipa: "feɪn", meaning: "veinzen" },
  { word: 'felicitous', ipa: "fɪˈlɪsɪtəs", meaning: "a felicitous example (well chosen)" },
  { word: 'feud', ipa: "fjuːd", meaning: "vete" },
  { word: 'fiend', ipa: "fiːnd", meaning: "a drug-fiend (addict)" },
  { word: 'fierce', ipa: "fɪəs", meaning: "fierce hatred" },
  { word: 'fiery', ipa: "ˈfaɪəri", meaning: "like fire; passionate" },
  { word: 'finance', ipa: "ˈfæmæns", meaning: "n/v" },
  { word: 'flour', ipa: "ˈflaʊə", meaning: "bloem(meel)" },
  { word: 'flourish',       ipa: "ˈflʌrɪʃ" },
  { word: 'fluid', ipa: "ˈfluːɪd", meaning: "n/adj., vloeistof; vloeibaar" },
  { word: 'foetus',         ipa: "ˈfiːtəs" },
  { word: 'foliage', ipa: "ˈfəʊlɪɪdʒ", meaning: "gebladerte, loof" },
  { word: 'forfeit', ipa: "ˈfɔːfɪt", meaning: "n/v/adj., ('t) verbeurd(e); verbeuren" },
  { word: 'forthwith', ipa: "fɔːθˈwɪθ", meaning: "immediately" },
  { word: 'franchise', ipa: "ˈfræntʃaɪz", meaning: "kiesrecht" },
  { word: 'fraud',          ipa: "frɔːd" },
  { word: 'freight',        ipa: "freɪt" },
  { word: 'frontier',       ipa: "ˈfrʌntɪə" },
  { word: 'fuchsia',        ipa: "ˈfjuːʃə" },
  { word: 'fugitive', ipa: "ˈfjuːdʒətɪv", meaning: "voortvluchtige" },
  { word: 'furlough', ipa: "ˈfɜːləʊ", meaning: "verlof" },
  // ── G (pages 211–212) ────────────────────────────────────────────────────
  { word: 'gaiety',         ipa: "ˈɡeɪəti" },
  { word: 'gambol', ipa: "ˈɡæmbl", meaning: "to frisk, skip (dartelen)" },
  { word: 'garage',         ipa: "ˈɡæraːʒ" },
  { word: 'garbage', ipa: "ˈɡaːbɪdʒ", meaning: "vuilnis, keukenafval" },
  { word: 'generosity', ipa: "ˈdʒenəˈrɒsəti", meaning: "edelmoedigheid, mildheid" },
  { word: 'genial', ipa: "ˈdʒiːnjəl", meaning: "sympathetic, sociable" },
  { word: 'genius', ipa: "ˈdʒiːnjəs", meaning: "genie" },
  { word: 'genuine', ipa: "ˈdʒenjʊm", meaning: "genuine regret, pearls" },
  { word: 'geographical',   ipa: "ˈdʒiːəˈɡræfɪkl" },
  { word: 'geometry',       ipa: "dʒɪˈɒmətri" },
  { word: 'gesture',        ipa: "ˈdʒestʃə" },
  { word: 'ghastly',        ipa: "ˈɡaːstli" },
  { word: 'ghoulish', ipa: "ˈɡuːlɪʃ", meaning: "gruesome; revolting" },
  { word: 'gigantic',       ipa: "dʒaɪˈɡæntɪk" },
  { word: 'gild', ipa: "ɡɪld", meaning: "vergulden" },
  { word: 'ginger', ipa: "ˈdʒɪndʒə", meaning: "gember; rood (haar)" },
  { word: 'giraffe',        ipa: "dʒɪˈraːf" },
  { word: 'glacier', ipa: "ˈɡlæsiə", meaning: "gletsjer" },
  { word: 'government',     ipa: "ˈɡʌvnmənt" },
  { word: 'grandeur',       ipa: "ˈɡrændʒə" },
  { word: 'granite',        ipa: "ˈɡrænɪt" },
  { word: 'gravity', ipa: "ˈɡrævəti", meaning: "the gravity of the situation" },
  { word: 'guillotine',     ipa: "ˈɡɪləˈtiːn" },
  { word: 'guitar',         ipa: "ɡɪˈtaː" },
  { word: 'gymnasium', ipa: "dʒɪmˈneɪzjəm", meaning: "gymnastiekzaal" },
  // ── H (page 212) ─────────────────────────────────────────────────────────
  { word: 'halt', ipa: "hɔːlt", meaning: "to call a halt to" },
  { word: 'handkerchief',   ipa: "ˈhæŋkətʃɪf" },
  { word: 'haphazard', ipa: "hæpˈhæzəd", meaning: "lukraak" },
  { word: 'hearse', ipa: "hɜːs", meaning: "carriage for coffin" },
  { word: 'height',         ipa: "haɪt" },
  { word: 'heinous', ipa: "ˈheɪnəs", meaning: "atrocious (of crime)" },
  { word: 'hemorrhage', ipa: "ˈhemərɪdʒ", meaning: "bloeding" },
  { word: 'hereditary', ipa: "hɪˈredɪtri", meaning: "erfelijk" },

  // ── Appendix 2 words (page 215) ──
  { word: 'irony', ipa: "ˈaɪərəni" },
  { word: 'Isaac', ipa: "ˈaɪzək" },
  { word: 'isle', ipa: "aɪl" },
  { word: 'Islington', ipa: "ˈɪzlɪŋtən" },
  { word: 'Israel', ipa: "ˈɪzreɪl" },
  { word: 'Israeli (n/adj.)', ipa: "ɪzˈreɪli" },
  { word: 'ivory', ipa: "ˈaɪvri", meaning: "Ivory Coast" },
  { word: 'ivy', ipa: "ˈaɪvi", meaning: "klimop" },
  { word: 'jackal', ipa: "ˈdʒækɔːl", meaning: "jakhals" },
  { word: 'jagged', ipa: "ˈdʒæɡɪd", meaning: "jagged rocks" },
  { word: 'jeopardise', ipa: "ˈdʒepədaɪz", meaning: "to endanger" },
  { word: 'jeopardy', ipa: "ˈdʒepədi", meaning: "danger" },
  { word: 'jersey', ipa: "ˈdʒɜːzi", meaning: "trui" },
  { word: 'Job', ipa: "dʒəʊb" },
  { word: 'khaki', ipa: "ˈkɑːki" },
  { word: 'kiosk', ipa: "ˈkiːɒsk", meaning: "telephone kiosk" },
  { word: 'laboratory', ipa: "ləˈbɒrətri" },
  { word: 'laity', ipa: "ˈleɪəti", meaning: "(de) leken(stand)" },
  { word: 'languid', ipa: "ˈlæŋɡwɪd", meaning: "lusteloos" },
  { word: 'Laos', ipa: "laʊs" },
  { word: 'lapel', ipa: "ləˈpel", meaning: "revers van een jasje" },
  { word: 'lass', ipa: "læs", meaning: "girl (cf. lad: boy)" },
  { word: 'lathe', ipa: "leɪð", meaning: "draaibank" },
  { word: 'launch (v/n)', ipa: "lɔːntʃ", meaning: "to launch a ship/rocket; motorbootje" },
  { word: 'launderette', ipa: "lɔːndəˈret" },
  { word: 'lava', ipa: "ˈlɑːvə" },
  { word: 'lavish (v/adj.)', ipa: "ˈlævɪʃ", meaning: "to lavish care on a child; a lavish production" },
  { word: 'lawyer', ipa: "ˈlɔɪə" },
  { word: 'lead (n/v)', ipa: "liːd", meaning: "leiden; to take the lead" },
  { word: 'lead (n)', ipa: "led", meaning: "lood" },
  { word: 'leant (pt/pp)', ipa: "lent" },
  { word: 'leapt (pt/pp)', ipa: "lept" },
  { word: 'learned (adj.)', ipa: "ˈlɜːnɪd", meaning: "a learned man, book" },
  { word: 'learned (pt/pp)', ipa: "lɜːnt" },
  { word: 'lease', ipa: "liːs", meaning: "pachten" },

  // ── Appendix 2 words (pages 213–231) ──
  { word: 'Hereford and Worcester', ipa: "ˈherəfəd ən ˈwʊstə", meaning: "English county" },
  { word: 'heresy', ipa: "ˈherəsi", meaning: "ketterij" },
  { word: 'heretic', ipa: "ˈherətɪk", meaning: "ketter" },
  { word: 'hermetic', ipa: "hɜːˈmetɪk" },
  { word: 'hero', ipa: "ˈhɪərəʊ" },
  { word: 'heroic', ipa: "hɪˈrəʊɪk" },
  { word: 'heroin', ipa: "ˈherəʊɪn", meaning: "heroïne" },
  { word: 'heroine', ipa: "ˈherəʊɪn", meaning: "heldin" },
  { word: 'heroism', ipa: "ˈherəʊɪzm" },
  { word: 'heron', ipa: "ˈherən", meaning: "reiger" },
  { word: 'Hertfordshire', ipa: "ˈhɑːfədʃə" },
  { word: 'hiatus', ipa: "haɪˈeɪtəs" },
  { word: 'hiccup', ipa: "ˈhɪkʌp", meaning: "hikken, de hik hebben" },
  { word: 'hideous', ipa: "ˈhɪdɪəs" },
  { word: 'Holborn', ipa: "ˈhəʊbən" },
  { word: 'homage', ipa: "ˈhɒmɪdʒ", meaning: "to pay homage to a great man" },
  { word: 'Homer', ipa: "ˈhəʊmə" },
  { word: 'honey', ipa: "ˈhʌni" },
  { word: 'horizon', ipa: "həˈraɪzn" },
  { word: 'horizontal', ipa: "ˈhɒrɪˈzɒntl" },
  { word: 'host', ipa: "həʊst" },
  { word: 'hostage', ipa: "ˈhɒstɪdʒ", meaning: "gijzelaar" },
  { word: 'hostess', ipa: "ˈhəʊstɪs" },
  { word: 'hotel', ipa: "həʊˈtel" },
  { word: 'house (v)', ipa: "haʊz", meaning: "the housing problem" },
  { word: 'hovel', ipa: "ˈhɒvl", meaning: "krot; schuurtje" },
  { word: 'hover', ipa: "ˈhɒvə" },
  { word: 'howl', ipa: "haʊl", meaning: "howling wolves" },
  { word: 'huge', ipa: "hjuːdʒ" },
  { word: 'Hugh', ipa: "hjuː", meaning: "(Christian name)" },
  { word: 'Hughes', ipa: "hjuːz", meaning: "(surname)" },
  { word: 'human', ipa: "ˈhjuːmən", meaning: "I\'m only human" },
  { word: 'humane', ipa: "hjuːˈmeɪn", meaning: "a humane treatment" },
  { word: 'hydrogen', ipa: "ˈhaɪdrədʒən", meaning: "H: waterstof" },
  { word: 'hyena', ipa: "haɪˈiːnə" },
  { word: 'hygiene', ipa: "ˈhaɪdʒiːn" },
  { word: 'hygienic', ipa: "haɪˈdʒiːnɪk" },
  { word: 'hypocrisy', ipa: "hɪˈpɒkrəsi", meaning: "schijnheiligheid" },
  { word: 'hypocrite', ipa: "ˈhɪpəkrɪt", meaning: "huichelaar" },
  { word: 'hypocritical', ipa: "ˈhɪpəˈkrɪtɪkl" },
  { word: 'Ian', ipa: "ˈiːən" },
  { word: 'idea', ipa: "aɪˈdɪə" },
  { word: 'ignorance', ipa: "ˈɪɡnərəns", meaning: "onwetendheid" },
  { word: 'illegible', ipa: "ɪˈledʒəbl", meaning: "onleesbaar" },
  { word: 'illusory', ipa: "ɪˈluːsəri", meaning: "illusive, deceptive" },
  { word: 'imbecile', ipa: "ˈɪmbəsiːl" },
  { word: 'impasse', ipa: "æmˈpɑːs" },
  { word: 'impediment', ipa: "ɪmˈpedɪmənt", meaning: "speech-impediment (-defect)" },
  { word: 'imperial', ipa: "ɪmˈpɪərɪəl" },
  { word: 'impetuous', ipa: "ɪmˈpetʃuəs", meaning: "onstuimig" },
  { word: 'implacable', ipa: "ɪmˈplækəbl", meaning: "onverzoenlijk" },
  { word: 'impoverish', ipa: "ɪmˈpɒvərɪʃ" },
  { word: 'impregnable', ipa: "ɪmˈpreɡnəbl", meaning: "onneembaar, onaantastbaar" },
  { word: 'incense', ipa: "ˈɪnsens", meaning: "wierook" },
  { word: 'indict', ipa: "ɪnˈdaɪt", meaning: "to accuse formally" },
  { word: 'indictment', ipa: "ɪnˈdaɪtmənt" },
  { word: 'indigenous', ipa: "ɪnˈdɪdʒɪnəs", meaning: "native" },
  { word: 'indigent', ipa: "ˈɪndɪdʒənt", meaning: "very poor" },
  { word: 'infamous', ipa: "ˈɪnfəməs", meaning: "schandelijk, berucht" },
  { word: 'ingenious', ipa: "ɪnˈdʒiːnjəs", meaning: "ingenieus" },
  { word: 'ingenuous', ipa: "ɪnˈdʒenjuəs", meaning: "innocent, natural" },
  { word: 'institution', ipa: "ˈɪnstɪˈtjuːʃn" },
  { word: 'integer', ipa: "ˈɪntədʒə", meaning: "an integer number" },
  { word: 'interest', ipa: "ˈɪntrəst" },
  { word: 'interesting', ipa: "ˈɪntrəstɪŋ" },
  { word: 'intestines', ipa: "ɪnˈtestɪnz", meaning: "ingewanden" },
  { word: 'intimacy', ipa: "ˈɪntɪməsi" },
  { word: 'intrepid', ipa: "ɪnˈtrepɪd", meaning: "onverschrokken" },
  { word: 'intricate', ipa: "ˈɪntrɪkət", meaning: "an intricate plot" },
  { word: 'intrigue', ipa: "ˈɪntriːɡ" },
  { word: 'intuition', ipa: "ˈɪntjuːˈɪʃn" },
  { word: 'intuitive', ipa: "ɪnˈtjuːətɪv" },
  { word: 'invalid (n/adj.)', ipa: "ˈɪnvəlɪd" },
  { word: 'invalid (adj.)', ipa: "ɪnˈvælɪd", meaning: "not valid" },
  { word: 'inveigh', ipa: "ɪnˈveɪ", meaning: "uitvaren tegen (i. against)" },
  { word: 'inventory', ipa: "ˈɪnvəntri", meaning: "inventaris" },
  { word: 'iodine', ipa: "ˈaɪədiːn", meaning: "jodium" },
  { word: 'ion', ipa: "ˈaɪən" },
  { word: 'Ireland', ipa: "ˈaɪələnd" },
  { word: 'iron', ipa: "ˈaɪən" },
  { word: 'ironic', ipa: "aɪˈrɒnɪk" },
  { word: 'ironmonger', ipa: "ˈaɪənmʌŋɡə", meaning: "ijzerwarenhandelaar" },
  { word: 'legislative', ipa: "ˈledʒɪslətɪv", meaning: "a legislative assembly" },
  { word: 'legislature', ipa: "ˈledʒɪsleɪtʃə", meaning: "wetgevende macht" },
  { word: 'Leicester', ipa: "ˈlestə" },
  { word: 'leisure', ipa: "ˈleʒə" },
  { word: 'Leonard', ipa: "ˈlenəd" },
  { word: 'leopard', ipa: "ˈlepəd" },
  { word: 'leper', ipa: "ˈlepə", meaning: "melaatse" },
  { word: 'leprosy', ipa: "ˈleprəsi", meaning: "melaatsheid, lepra" },
  { word: 'lettuce', ipa: "ˈletəs", meaning: "sla" },
  { word: 'Levi', ipa: "ˈliːvaɪ" },
  { word: 'levity', ipa: "ˈlevəti", meaning: "lichtzinnigheid" },
  { word: 'lieutenant', ipa: "lefˈtenənt", meaning: "(British Army)" },
  { word: 'lilac', ipa: "ˈlaɪlək", meaning: "sering; lila" },
  { word: 'Lincoln', ipa: "ˈlɪŋkən" },
  { word: 'linen', ipa: "ˈlɪmɪn" },
  { word: 'linger', ipa: "ˈlɪŋɡə", meaning: "dralen, blijven hangen" },
  { word: 'liqueur', ipa: "lɪˈkjuə", meaning: "likeur" },
  { word: 'liquid', ipa: "ˈlɪkwɪd" },
  { word: 'liquor', ipa: "ˈlɪkə", meaning: "AmE for BrE spirits" },
  { word: 'liquorice', ipa: "ˈlɪkərɪʃ", meaning: "drop" },
  { word: 'live (adj.)', ipa: "laɪv", meaning: "a live broadcast" },
  { word: 'live (v)', ipa: "lɪv" },
  { word: 'livelihood', ipa: "ˈlaɪvlɪhʊd", meaning: "to earn an honest livelihood" },
  { word: 'livelong', ipa: "ˈlɪvlɒŋ", meaning: "the livelong day" },
  { word: 'liver', ipa: "ˈlɪvə", meaning: "lever" },
  { word: 'livestock', ipa: "ˈlaɪvstɒk", meaning: "vee" },
  { word: 'livid', ipa: "ˈlɪvɪd", meaning: "furious" },
  { word: 'lizard', ipa: "ˈlɪzəd", meaning: "hagedis" },
  { word: 'loathe', ipa: "ˈləʊð", meaning: "she loathed that kind of food" },
  { word: 'loch', ipa: "lɒk", meaning: "lake (in Scotland)" },
  { word: 'longevity', ipa: "lɒnˈdʒevəti", meaning: "lang leven" },
  { word: 'longitude', ipa: "ˈlɒndʒɪtjuːd" },
  { word: 'loose (adj.)', ipa: "luːs" },
  { word: 'loosen (v)', ipa: "ˈluːsn", meaning: "to loosen a screw" },
  { word: 'lose (v)', ipa: "luːz", meaning: "to lose one\'s job" },
  { word: 'loth', ipa: "ləʊθ", meaning: "to be loth to do something" },
  { word: 'lough', ipa: "lɒk", meaning: "lake (in Ireland)" },
  { word: 'lounge (n/v)', ipa: "laʊndʒ", meaning: "lanterfanten; a hotel lounge" },
  { word: 'love', ipa: "lʌv" },
  { word: 'lower (v/adj.)', ipa: "ˈləʊə", meaning: "comp. of low; verlagen" },
  { word: 'lour (lower) (v)', ipa: "ˈlaʊə", meaning: "look threatening" },
  { word: 'lucrative', ipa: "ˈluːkrətɪv" },
  { word: 'lugubrious', ipa: "luˈɡuːbrɪəs" },
  { word: 'lunatic', ipa: "ˈluːnətɪk" },
  { word: 'luxurious', ipa: "lʌɡˈʒuərɪəs" },
  { word: 'luxury', ipa: "ˈlʌkʃri" },
  { word: 'macabre', ipa: "məˈkɑːbrə" },
  { word: 'machination', ipa: "ˈmækɪˈneɪʃn", meaning: "evil plot(ting)" },
  { word: 'machismo', ipa: "məˈtʃɪzməʊ", meaning: "tendency to display masculine behaviour-pattern" },
  { word: 'macho (n/adj.)', ipa: "ˈmætʃəʊ", meaning: "(man) showing machismo" },
  { word: 'magazine', ipa: "ˈmæɡəˈziːn" },
  { word: 'magistrate', ipa: "ˈmædʒɪstrət" },
  { word: 'magnetism', ipa: "ˈmæɡnətɪzm" },
  { word: 'mahogany', ipa: "məˈhɒɡəni", meaning: "mahoniehout(en)" },
  { word: 'malevolent', ipa: "məˈlevələnt", meaning: "kwaadwillig" },
  { word: 'malice', ipa: "ˈmælɪs", meaning: "to bear malice (wrok koesteren)" },
  { word: 'mall', ipa: "mɔːl", meaning: "a shopping mall" },
  { word: 'the Mall', ipa: "mæl" },
  { word: 'managerial', ipa: "ˈmænədʒˈɪərɪəl", meaning: "a managerial position" },
  { word: 'mania', ipa: "ˈmeɪnjə" },
  { word: 'maniac', ipa: "ˈmeɪnɪæk" },
  { word: 'maniacal', ipa: "məˈnaɪəkl" },
  { word: 'manifold', ipa: "ˈmænɪfəʊld", meaning: "veelvoudig" },
  { word: 'manor', ipa: "ˈmænə" },
  { word: 'manoeuvre', ipa: "məˈnuːvə" },
  { word: 'manure', ipa: "məˈnjuə", meaning: "mest (kunstmest: fertiliser)" },
  { word: 'marine', ipa: "məˈriːn" },
  { word: 'mariner', ipa: "ˈmærənə", meaning: "literary: sailor" },
  { word: 'marital', ipa: "ˈmærətl", meaning: "echtelijk" },
  { word: 'maritime', ipa: "ˈmærətaɪm", meaning: "a maritime power" },
  { word: 'marquess (marquis)', ipa: "ˈmɑːkwɪs" },
  { word: 'marriage', ipa: "ˈmærɪdʒ" },
  { word: 'masculine', ipa: "ˈmæskjʊlɪn" },
  { word: 'mason', ipa: "ˈmeɪsn", meaning: "a freemason" },
  { word: 'mask', ipa: "mɑːsk" },
  { word: 'masquerade', ipa: "ˈmæskəˈreɪd" },
  { word: 'massage', ipa: "ˈmæsɑːʒ" },
  { word: 'maths', ipa: "mæθs" },
  { word: 'matrix', ipa: "ˈmeɪtrɪks" },
  { word: 'mausoleum', ipa: "ˈmɔːsəˈliːəm" },
  { word: 'mayor', ipa: "meə", meaning: "the Lord Mayor (of London)" },
  { word: 'meander (v)', ipa: "miˈændə", meaning: "kronkelen" },
  { word: 'mechanic', ipa: "mɪˈkænɪk", meaning: "monteur" },
  { word: 'medicine', ipa: "ˈmedsn", meaning: "to study medicine" },
  { word: 'medieval', ipa: "ˈmediˈiːvl" },
  { word: 'mediocre', ipa: "ˈmiːdiˈəʊkə" },
  { word: 'mediocrity', ipa: "ˈmiːdiˈɒkrəti" },
  { word: 'mediterranean', ipa: "ˈmedɪtəˈreɪmjən", meaning: "the Mediterranean" },
  { word: 'melancholic', ipa: "ˈmelənˈkɒlɪk" },
  { word: 'melancholy', ipa: "ˈmelənkəli" },
  { word: 'melon', ipa: "ˈmelən" },
  { word: 'memoir', ipa: "ˈmemwɑː" },
  { word: 'mercenary', ipa: "ˈmɜːsnri", meaning: "huursoldaat" },
  { word: 'Merseyside', ipa: "ˈmɜːzɪsaɪd", meaning: "English county" },
  { word: 'Messiah', ipa: "mɪˈsaɪə" },
  { word: 'Messrs', ipa: "ˈmesəz", meaning: "pl. of Mr" },
  { word: 'metropolis', ipa: "mɪˈtrɒpəlɪs" },
  { word: 'metropolitan', ipa: "ˈmetrəˈpɒlɪtən", meaning: "the ~ police" },
  { word: 'migrate', ipa: "maɪˈɡreɪt" },
  { word: 'migratory', ipa: "ˈmaɪɡrətri", meaning: "migratory birds" },
  { word: 'militia', ipa: "mɪˈlɪʃə" },
  { word: 'miniature', ipa: "ˈmɪnɪtʃə" },
  { word: 'minute (n)', ipa: "ˈmɪnɪt", meaning: "pl. also notulen" },
  { word: 'minute (adj.)', ipa: "maɪˈnjuːt", meaning: "extremely small" },
  { word: 'miscellaneous', ipa: "ˈmɪsəˈlemjəs", meaning: "gemengd" },
  { word: 'miscellany', ipa: "mɪˈseləni", meaning: "mengeling" },
  { word: 'mischief', ipa: "ˈmɪstʃɪf", meaning: "onheil, kattenkwaad" },
  { word: 'mischievous', ipa: "ˈmɪstʃɪvəs" },
  { word: 'miser', ipa: "ˈmaɪzə", meaning: "vrek" },
  { word: 'miserable', ipa: "ˈmɪzrəbl" },
  { word: 'mistake', ipa: "mɪˈsteɪk" },
  { word: 'mistletoe', ipa: "ˈmɪsltəʊ" },
  { word: 'mitigate', ipa: "ˈmɪtɪɡeɪt", meaning: "mitigating circumstances" },
  { word: 'molest', ipa: "məˈlest" },
  { word: 'monarch', ipa: "ˈmɒnək" },
  { word: 'monetary', ipa: "ˈmʌnətri" },
  { word: 'money', ipa: "ˈmʌni" },
  { word: 'mongrel', ipa: "ˈmʌŋɡrəl", meaning: "bastaard" },
  { word: 'monk', ipa: "mʌŋk", meaning: "monnik" },
  { word: 'monkey', ipa: "ˈmʌŋki" },
  { word: 'monogram', ipa: "ˈmɒnəɡræm" },
  { word: 'month', ipa: "mʌnθ" },
  { word: 'Montreal', ipa: "ˈmɒntriˈɔːl" },
  { word: 'morale (n)', ipa: "məˈrɑːl", meaning: "moreel" },
  { word: 'morass', ipa: "məˈræs", meaning: "marsh" },
  { word: 'mortgage', ipa: "ˈmɔːɡɪdʒ", meaning: "hypotheek" },
  { word: 'mosquito', ipa: "məˈskiːtəʊ" },
  { word: 'mould', ipa: "məʊld", meaning: "mal, vorm; schimmel" },
  { word: 'mourn', ipa: "mɔːn", meaning: "rouwen, treuren" },
  { word: 'moustache', ipa: "məˈstɑːʃ" },
  { word: 'mow', ipa: "məʊ", meaning: "a lawnmower" },
  { word: 'muscle', ipa: "mʌsl" },
  { word: 'muscular', ipa: "ˈmʌskjʊlə" },
  { word: 'myriad', ipa: "ˈmɪrɪəd", meaning: "very great number" },
  { word: 'myth', ipa: "mɪθ", meaning: "mythe" },
  { word: 'Naipaul', ipa: "ˈnaɪpɔːl", meaning: "V.S. Naipaul" },
  { word: 'narrate', ipa: "nəˈreɪt", meaning: "verhalen" },
  { word: 'narrative (n/adj.)', ipa: "ˈnærətɪv", meaning: "verhaal, verslag" },
  { word: 'NASA', ipa: "ˈnæsə" },
  { word: 'nasty', ipa: "ˈnɑːsti" },
  { word: 'nausea', ipa: "ˈnɔːsjə", meaning: "misselijkheid, walging" },
  { word: 'negotiate', ipa: "nɪˈɡəʊʃɪeɪt" },
  { word: 'negotiation', ipa: "nɪˈɡəʊʃɪˈeɪʃn" },
  { word: 'neigh', ipa: "neɪ", meaning: "hinniken" },
  { word: 'newspaper', ipa: "ˈnjuːspeɪpə" },
  { word: 'niche', ipa: "nɪtʃ", meaning: "nis" },
  { word: 'Nigel', ipa: "ˈnaɪdʒl" },
  { word: 'Nike', ipa: "ˈnaɪki" },
  { word: 'none', ipa: "nʌn" },
  { word: 'nothing', ipa: "ˈnʌθɪŋ" },
  { word: 'noughts and crosses', ipa: "ˈnɔːts ən ˈkrɒsɪz", meaning: "boter, kaas en eieren" },
  { word: 'nourish', ipa: "ˈnʌrɪʃ" },
  { word: 'nuisance', ipa: "ˈnjuːsns", meaning: "(over)last, lastpost" },
  { word: 'nursery', ipa: "ˈnɜːsri", meaning: "kinderkamer; kwekerij" },
  { word: 'oath', ipa: "əʊθ", meaning: "an oath of allegiance" },
  { word: 'obese', ipa: "əʊˈbiːs", meaning: "corpulent, zwaarlijvig" },
  { word: 'obesity', ipa: "əʊˈbiːsəti" },
  { word: 'obligatory', ipa: "əˈblɪɡətri" },
  { word: 'oblique', ipa: "əˈbliːk", meaning: "schuin; scheef (hoek)" },
  { word: 'oboe', ipa: "ˈəʊbəʊ", meaning: "musical instrument (hobo)" },
  { word: 'obsequies', ipa: "ˈɒbsəkwɪz", meaning: "funeral ceremonies (uitvaart)" },
  { word: 'obsequious', ipa: "əbˈzeɪv", meaning: "kruiperig, onderdanig" },
  { word: 'observation', ipa: "ˈɒbzəˈveɪʃn" },
  { word: 'observe', ipa: "əbˈzɜːv" },
  { word: 'obsolete', ipa: "ˈɒbsəliːt", meaning: "verouderd" },
  { word: 'obtuse', ipa: "əbˈtjuːs", meaning: "an obtuse angle; blunt (bot)" },
  { word: 'octave', ipa: "ˈɒktɪv" },
  { word: 'October', ipa: "ɒkˈtəʊbə" },
  { word: 'odour (n)', ipa: "ˈəʊdə", meaning: "smell" },
  { word: 'off-licence', ipa: "ˈɒf laɪsns", meaning: "slijterij" },
  { word: 'olive', ipa: "ˈɒlɪv" },
  { word: 'omen', ipa: "ˈəʊmən", meaning: "voorteken" },
  { word: 'ominous', ipa: "ˈɒmɪnəs", meaning: "foreboding evil, threatening" },
  { word: 'omit', ipa: "əˈmɪt", meaning: "leave out; fail to do" },
  { word: 'omnipotent', ipa: "ɒmˈnɪpətənt", meaning: "almachtig" },
  { word: 'omniscient', ipa: "ɒmˈnɪʃnt", meaning: "alwetend" },
  { word: 'onion', ipa: "ˈʌnjən" },
  { word: 'opportune', ipa: "ˈɒpətjuːn" },
  { word: 'opulent', ipa: "ˈɒpjʊlənt", meaning: "opulent vegetation (weelderig)" },
  { word: 'orator', ipa: "ˈɒrətə" },
  { word: 'orchard', ipa: "ˈɔːtʃəd", meaning: "boomgaard" },
  { word: 'orchestra', ipa: "ˈɔːkɪstrə" },
  { word: 'orchid', ipa: "ˈɔːkɪd", meaning: "orchidee" },
  { word: 'ornament (n/v)', ipa: "ˈɔːnəmənt" },
  { word: 'oust', ipa: "aʊst", meaning: "(president) uit ambt stoten" },
  { word: 'oven', ipa: "ˈʌvn" },
  { word: 'overhead (adv.)', ipa: "ˈəʊvəˈhed" },
  { word: 'overhead (n/adj.)', ipa: "ˈəʊvəhed", meaning: "overhead charges (vaste lasten)" },
  { word: 'oxygen', ipa: "ˈɒksɪdʒən", meaning: "O: zuurstof" },
  { word: 'pacific', ipa: "piː" },
  { word: 'pageant', ipa: "pəˈsɪfɪk", meaning: "groots schouwspel, optocht" },
  { word: 'palsy', ipa: "ˈpædʒənt", meaning: "paralysis (verlamming)" },
  { word: 'panacea', ipa: "ˈpɔːlzi", meaning: "remedy for all troubles" },
  { word: 'pant', ipa: "ˈpænəˈsɪə", meaning: "hijgen" },
  { word: 'parachute', ipa: "pænt" },
  { word: 'paradise', ipa: "ˈpærəʃuːt" },
  { word: 'parasite', ipa: "ˈpærədaɪs" },
  { word: 'parsley', ipa: "ˈpærəsaɪt", meaning: "peterselie" },
  { word: 'pastry', ipa: "ˈpɑːsli", meaning: "gebak" },
  { word: 'pasty (n)', ipa: "ˈpeɪstri", meaning: "pasteitje" },
  { word: 'pathetic', ipa: "ˈpæsti", meaning: "aandoenlijk; bedroevend slecht" },
  { word: 'patriarch', ipa: "pəˈθetɪk" },
  { word: 'patriot', ipa: "ˈpeɪtrɪɑːk" },
  { word: 'patriotic', ipa: "ˈpætrɪət" },
  { word: 'patrol', ipa: "ˈpætrɪˈɒtɪk", meaning: "patrouille" },
  { word: 'patron', ipa: "ˈpætrəʊ", meaning: "patrouille" },
  { word: 'patronise', ipa: "ˈpætərnaɪz", meaning: "beschermheer; vaste klant" },
  { word: 'peasant', ipa: "ˈpeznt" },
  { word: 'pedal', ipa: "ˈpedl" },
  { word: 'pedant', ipa: "ˈpednt", meaning: "betweter, muggenzifter" },
  { word: 'pedestal', ipa: "ˈpedɪstl", meaning: "voetstuk" },
  { word: 'pedigree', ipa: "ˈpedɪɡriː", meaning: "stamboom" },
  { word: 'pejorative', ipa: "pɪˈdʒɒrətɪv", meaning: "ongunstig (van bijbetekenis)" },
  { word: 'Peking', ipa: "piːˈkɪŋ" },
  { word: 'penal (adj.)', ipa: "ˈpiːnl", meaning: "straf-" },
  { word: 'perjury', ipa: "ˈpɜːdʒəri", meaning: "meineed" },
  { word: 'perpetual', ipa: "pəˈpetʃuəl", meaning: "perpetual snow" },
  { word: 'perseverance', ipa: "ˈpɜːsəˈvɪərəns", meaning: "volharding" },
  { word: 'personnel', ipa: "ˈpɜːsəˈnel", meaning: "personnel manager" },
  { word: 'persuade', ipa: "pəˈsweɪd" },
  { word: 'petty', ipa: "ˈpeti", meaning: "petty cash; petty officer" },
  { word: 'petulant', ipa: "ˈpetjʊlənt", meaning: "prikkelbaar, kribbig" },
  { word: 'Pharao', ipa: "ˈfeərəʊ" },
  { word: 'pheasant', ipa: "ˈfeznt" },
  { word: 'Philippines', ipa: "ˈfɪlɪpiːnz" },
  { word: 'philosophy', ipa: "fɪˈlɒsəfi" },
  { word: 'physique', ipa: "fɪˈziːk" },
  { word: 'pianist', ipa: "ˈpɪənɪst" },
  { word: 'piano', ipa: "pɪˈænəʊ" },
  { word: 'piebald', ipa: "ˈpaɪbɔːld", meaning: "a piebald horse (bont)" },
  { word: 'pier', ipa: "pɪə", meaning: "pier" },
  { word: 'pint', ipa: "paɪnt" },
  { word: 'pious', ipa: "ˈpaɪəs" },
  { word: 'pirate (n/v)', ipa: "ˈpaɪərət" },
  { word: 'pivot', ipa: "ˈpɪvət", meaning: "spil" },
  { word: 'placid', ipa: "ˈplæsɪd", meaning: "calm" },
  { word: 'plagiarism', ipa: "ˈpleɪdʒərɪzm", meaning: "plagiaat" },
  { word: 'pleasure', ipa: "ˈpleʒə" },
  { word: 'plimsolls', ipa: "ˈplɪmslz", meaning: "gympies" },
  { word: 'plough', ipa: "plaʊ" },
  { word: 'plover', ipa: "ˈplʌvə", meaning: "kievit" },
  { word: 'pneumatic', ipa: "njuːˈmætɪk", meaning: "a pneumatic drill" },
  { word: 'pneumonia', ipa: "njuːˈməʊnjə", meaning: "longontsteking" },
  { word: 'poignant', ipa: "ˈpɔɪm(j)ənt", meaning: "aangrijpend, scherp" },
  { word: 'polemic (n/adj.)', ipa: "pəˈlemɪk" },
  { word: 'polish', ipa: "ˈpɒlɪʃ" },
  { word: 'Polish', ipa: "ˈpəʊlɪʃ" },
  { word: 'poll', ipa: "pəʊl", meaning: "public-opinion poll" },
  { word: 'pony', ipa: "ˈpəʊni" },
  { word: 'porcelain', ipa: "ˈpɔːslɪn" },
  { word: 'porpoise', ipa: "ˈpɔːpəs", meaning: "bruinvis" },
  { word: 'portend (v)', ipa: "pɔːˈtend", meaning: "be a sign of" },
  { word: 'portent', ipa: "ˈpɔːtent", meaning: "voorteken" },
  { word: 'portmanteau', ipa: "pɔːtˈmæntəʊ", meaning: "valies" },
  { word: 'portrait', ipa: "ˈpɔːtrɪt" },
  { word: 'portray', ipa: "pɔːˈtreɪ" },
  { word: 'postage', ipa: "ˈpəʊstɪdʒ" },
  { word: 'posterior', ipa: "pɒˈstɪərɪə", meaning: "nageslacht" },
  { word: 'posterity', ipa: "pɒˈsterəti" },
  { word: 'posture', ipa: "ˈpɒstʃə", meaning: "houding, stand" },
  { word: 'pour', ipa: "pɔː", meaning: "to pour a cup of tea" },
  { word: 'practise (n)', ipa: "ˈpræktɪs" },
  { word: 'practise (v)', ipa: "ˈpræktɪs" },
  { word: 'prayer', ipa: "preə", meaning: "The Lord\'s Prayer" },
  { word: 'precedence', ipa: "ˈpresɪdəns", meaning: "to take precedence of (over)" },
  { word: 'precedent', ipa: "ˈpresɪdənt" },
  { word: 'precious', ipa: "ˈpreʃəs" },
  { word: 'précis', ipa: "ˈpreɪsiː", meaning: "tekstsamenvatting" },
  { word: 'precise', ipa: "prɪˈsaɪs" },
  { word: 'precocious', ipa: "prɪˈkəʊʃəs", meaning: "vroegrijp" },
  { word: 'precocity', ipa: "prɪˈkɒsəti" },
  { word: 'preface', ipa: "ˈprefɪs", meaning: "the preface of a book" },
  { word: 'prelate', ipa: "ˈprelɪt" },
  { word: 'premature', ipa: "ˈpremətʃuə" },
  { word: 'presentiment', ipa: "prɪˈzentɪmənt", meaning: "voorgevoel" },
  { word: 'preserve', ipa: "prɪˈzɜːv" },
  { word: 'preservation', ipa: "ˈprezəˈveɪʃn" },
  { word: 'pressure', ipa: "ˈpreʃə" },
  { word: 'prestige', ipa: "preˈstiːʒ" },
  { word: 'prestigious', ipa: "preˈstɪdʒəs" },
  { word: 'presume', ipa: "prɪˈzjuːm" },
  { word: 'prevalent', ipa: "ˈprevələnt", meaning: "heersend" },
  { word: 'primer', ipa: "ˈpraɪmə" },
  { word: 'privacy', ipa: "ˈprɪvəsi" },
  { word: 'private (n/adj.)', ipa: "ˈpraɪvɪt" },
  { word: 'privy', ipa: "ˈprɪvi" },
  { word: 'procedure', ipa: "prəˈsiːdʒə" },
  { word: 'proceed (v)', ipa: "prəˈsiːd" },
  { word: 'proceeds', ipa: "ˈprəʊsɪdz", meaning: "opbrengst" },
  { word: 'profile', ipa: "ˈprəʊfaɪl", meaning: "also: brief biography" },
  { word: 'profuse', ipa: "prəˈfjuːs", meaning: "profuse gratitude (overvloeding)" },
  { word: 'prolific', ipa: "prəˈlɪfɪk", meaning: "a prolific author" },
  { word: 'promenade', ipa: "ˈprɒməˈnɑːd" },
  { word: 'promote', ipa: "prəˈməʊt" },
  { word: 'prophecy (n)', ipa: "ˈprɒfəsi" },
  { word: 'prophesy (v)', ipa: "ˈprɒfɪsaɪ" },
  { word: 'prophet', ipa: "ˈprɒfɪt" },
  { word: 'prosaic', ipa: "prəˈzeɪɪk" },
  { word: 'prosecute', ipa: "ˈprɒsɪkjuːt" },
  { word: 'protein', ipa: "ˈprəʊtiːn" },
  { word: 'psalm', ipa: "sɑːm" },
  { word: 'pseudonym', ipa: "ˈsjuːdənɪm" },
  { word: 'psychiatric', ipa: "ˈsaɪkɪˈætrɪk" },
  { word: 'psychiatrist', ipa: "saɪˈkætrɪst" },
  { word: 'pudding', ipa: "ˈpʊdɪŋ" },
  { word: 'pulley', ipa: "ˈpʊli", meaning: "katrol" },
  { word: 'pullover', ipa: "ˈpʊləʊvə" },
  { word: 'pulp', ipa: "pʌlp" },
  { word: 'pulpit', ipa: "ˈpʊlpɪt", meaning: "preekstoel" },
  { word: 'purchase (n/v)', ipa: "ˈpɜːtʃəs" },
  { word: 'purgatory', ipa: "ˈpɜːɡətri", meaning: "vagevuur" },
  { word: 'putrid', ipa: "ˈpjuːtrɪd", meaning: "rotten, ill-smelling" },
  { word: 'putti', ipa: "pʊti", meaning: "sg. putto: naakt kinderfiguurtje" },
  { word: 'putting-green', ipa: "ˈpʌtɪŋ ɡriːn", meaning: "smooth area of lawn round a hole (golf)" },
  { word: 'putty', ipa: "ˈpʌti", meaning: "stopverf" },
  { word: 'pyramid', ipa: "ˈpɪrəmɪd" },
  { word: 'quack', ipa: "kwæk", meaning: "kwakzalver" },
  { word: 'quadruped', ipa: "ˈkwɒdrʊped", meaning: "viervoeter" },
  { word: 'qualm', ipa: "kwɑːm", meaning: "misgiving" },
  { word: 'quarrel (n/v)', ipa: "ˈkwɒrəl" },
  { word: 'quay', ipa: "kiː" },
  { word: 'questionnaire', ipa: "ˈkwestʃəˈneə", meaning: "vragenlijst" },
  { word: 'quoth', ipa: "kwəʊθ", meaning: "1st/3rd p sg pt (= said)" },
  { word: 'quotient', ipa: "ˈkwəʊʃnt" },
  { word: 'rabbi', ipa: "ˈræbaɪ" },
  { word: 'raft', ipa: "rɑːft", meaning: "(houten) vlot" },
  { word: 'ragged', ipa: "ˈræɡɪd", meaning: "haveloos; ruw, onregelmatig" },
  { word: 'raisin', ipa: "ˈreɪzn", meaning: "rozijn" },
  { word: 'Ralph', ipa: "rælf" },
  { word: 'ranch', ipa: "rɑːntʃ" },
  { word: 'rascal', ipa: "ˈrɑːskl" },
  { word: 'raspberry', ipa: "ˈrɑːzbri", meaning: "framboos" },
  { word: 'ratio', ipa: "ˈreɪʃɪəʊ", meaning: "verhouding" },
  { word: 'ration', ipa: "ˈræʃn" },
  { word: 'rational', ipa: "ˈræʃnl" },
  { word: 'ravine', ipa: "rəˈviːn" },
  { word: 'ravish', ipa: "ˈrævɪʃ", meaning: "verrukken; verkrachten" },
  { word: 'realm', ipa: "relm", meaning: "koninkrijk, (fig.) gebied" },
  { word: 'reassure', ipa: "ˈriːəˈʃɔː" },
  { word: 'receipt', ipa: "rɪˈsiːt", meaning: "ontvangst; kwitantie" },
  { word: 'recipe', ipa: "ˈresəpi", meaning: "(keuken) recept" },
  { word: 'recollect', ipa: "ˈrekəˈlekt", meaning: "remember" },
  { word: 'reconcile', ipa: "ˈrekənsaɪl" },
  { word: 'reconnaissance', ipa: "rɪˈkɒnɪsns", meaning: "a reconnaissance plane" },
  { word: 'reflex', ipa: "ˈriːfleks", meaning: "conditioned reflex" },
  { word: 'refuge', ipa: "ˈrefjuːdʒ", meaning: "street-refuge (vluchtheuvel)" },
  { word: 'refugee', ipa: "ˈrefjuːˈdʒiː", meaning: "vluchteling" },
  { word: 'regime', ipa: "reɪˈʒiːm" },
  { word: 'regiment', ipa: "ˈredʒɪmənt" },
  { word: 'rehabilitate', ipa: "ˈriːəˈbɪlɪteɪt" },
  { word: 'rehearse', ipa: "rɪˈhɜːs", meaning: "a dress rehearsal" },
  { word: 'release', ipa: "rɪˈliːs" },
  { word: 'relish', ipa: "ˈrelɪʃ", meaning: "he didn\'t relish the idea" },
  { word: 'remedy (n/v)', ipa: "ˈremədi" },
  { word: 'renaissance', ipa: "rɪˈneɪsns" },
  { word: 'rendez-vous', ipa: "ˈrɒndɪvuː", meaning: "meeting(-place)" },
  { word: 'renovation', ipa: "ˈrenəˈveɪʃn" },
  { word: 'repertoire', ipa: "ˈrepətwɑː" },
  { word: 'replica', ipa: "ˈreplɪkə" },
  { word: 'represent', ipa: "ˈreprɪˈzent" },
  { word: 'research', ipa: "rɪˈsɜːtʃ" },
  { word: 'reservoir', ipa: "ˈrezəvwɑː" },
  { word: 'reside', ipa: "rɪˈzaɪd" },
  { word: 'residence', ipa: "ˈrezɪdəns" },
  { word: 'resign', ipa: "rɪˈzaɪn" },
  { word: 'resin', ipa: "ˈrezɪn", meaning: "hars" },
  { word: 'resolute', ipa: "ˈrezəluːt" },
  { word: 'resound', ipa: "rɪˈzaʊnd", meaning: "a resounding success" },
  { word: 'restaurant', ipa: "ˈrestərɒnt" },
  { word: 'resurrection', ipa: "ˈrezəˈrekʃn" },
  { word: 'retail (n)', ipa: "ˈriːteɪl", meaning: "detailhandel" },
  { word: 'retaliate', ipa: "rɪˈtælɪeɪt", meaning: "wraak nemen, vergelden" },
  { word: 'reticent', ipa: "ˈretɪsnt", meaning: "terughoudend, gesloten" },
  { word: 'revel', ipa: "ˈrevl", meaning: "to make merry" },
  { word: 'revere', ipa: "rɪˈvɪə", meaning: "regard with great respect" },
  { word: 'revolt (n/v)', ipa: "rɪˈvəʊlt" },
  { word: 'Reynolds', ipa: "ˈrenlz" },
  { word: 'rhetoric', ipa: "ˈretərɪk" },
  { word: 'rhetorical', ipa: "rɪˈtɒrɪkl" },
  { word: 'rheumatism', ipa: "ˈruːmətɪzm" },
  { word: 'rhubarb', ipa: "ˈruːbɑːb", meaning: "rabarber" },
  { word: 'ricochet (n/v)', ipa: "ˈrɪkəʃeɪ", meaning: "afketsen" },
  { word: 'rigid', ipa: "ˈrɪdʒɪd" },
  { word: 'rivulet', ipa: "ˈrɪvjʊlɪt" },
  { word: 'roll', ipa: "rəʊl" },
  { word: 'romance', ipa: "rəˈmæns" },
  { word: 'rouge', ipa: "ruːʒ" },
  { word: 'rough', ipa: "rʌf" },
  { word: 'route', ipa: "ruːt" },
  { word: 'row (n/v)', ipa: "raʊ", meaning: "quarrel" },
  { word: 'row (n/v)', ipa: "rəʊ", meaning: "rij; roeien" },
  { word: 'rugged', ipa: "ˈrʌɡɪd", meaning: "rough, irregular; rocky" },
  { word: 'sabotage', ipa: "ˈsæbətɑːʒ" },
  { word: 'sacred', ipa: "ˈseɪkrɪd" },
  { word: 'sacrifice (n/v)', ipa: "ˈsækrɪfaɪs" },
  { word: 'sacrilege', ipa: "ˈsæˈkrɪlɪdʒ", meaning: "heiligschennis" },
  { word: 'saga', ipa: "ˈsɑːɡə" },
  { word: 'Sahara', ipa: "səˈhɑːrə" },
  { word: 'Salisbury', ipa: "ˈsɔːlzbri" },
  { word: 'saliva', ipa: "səˈlaɪvə", meaning: "speeksel" },
  { word: 'salmon', ipa: "ˈsæmən" },
  { word: 'sample', ipa: "ˈsɑːmpl", meaning: "monster, staal(tje)" },
  { word: 'sandwich', ipa: "ˈsænwɪdʒ" },
  { word: 'Sarah', ipa: "ˈseərə" },
  { word: 'sarcasm', ipa: "ˈsɑːkæzm" },
  { word: 'sardine', ipa: "sɑːˈdiːn" },
  { word: 'satire', ipa: "ˈsætaɪə" },
  { word: 'saucepan', ipa: "ˈsɔːspən", meaning: "steelpan" },
  { word: 'Saudi Arabia', ipa: "ˈsaʊdi əˈreɪbjə" },
  { word: 'Saviour', ipa: "ˈseɪvjə" },
  { word: 'scald', ipa: "skɔːld", meaning: "hurt, clean with hot liquid" },
  { word: 'scant', ipa: "skænt", meaning: "to pay scant attention to sth." },
  { word: 'scanty', ipa: "ˈskænti", meaning: "a scanty meal, bathing-dress" },
  { word: 'scarce', ipa: "skeəs" },
  { word: 'scent (n/v)', ipa: "sent", meaning: "he scented the danger" },
  { word: 'sceptic', ipa: "ˈskeptɪk" },
  { word: 'sceptre', ipa: "ˈseptə" },
  { word: 'schedule', ipa: "ˈʃedjuːl" },
  { word: 'scheme (n/v)', ipa: "skiːm" },
  { word: 'schism', ipa: "ˈsɪzm" },
  { word: 'schizophrenia', ipa: "ˈskɪtsəʊˈfriːnjə" },
  { word: 'schizophrenic', ipa: "ˈskɪtsəʊˈfrenɪk" },
  { word: 'sclerosis', ipa: "skləˈrəʊsɪs", meaning: "(ader)verkalking" },
  { word: 'scold', ipa: "skəʊld", meaning: "een standje geven" },
  { word: 'scythe', ipa: "saɪð", meaning: "zeis" },
  { word: 'Sean', ipa: "ʃɔːn" },
  { word: 'senator', ipa: "ˈsenətə" },
  { word: 'senile', ipa: "ˈsiːnaɪl" },
  { word: 'Seoul', ipa: "səʊl" },
  { word: 'sequel', ipa: "ˈsiːkwəl", meaning: "vervolg" },
  { word: 'series (sg/pl)', ipa: "ˈsɪərɪːz" },
  { word: 'sever', ipa: "ˈsevə", meaning: "to sever connections" },
  { word: 'sew', ipa: "səʊ" },
  { word: 'sewer', ipa: "ˈsuːə", meaning: "riool" },
  { word: 'Sheerness', ipa: "ˈʃɪəˈnes" },
  { word: 'sheik (n)', ipa: "ʃeɪk" },
  { word: 'shone (pp)', ipa: "ʃɒn" },
  { word: 'shove', ipa: "ʃʌv" },
  { word: 'shovel', ipa: "ˈʃʌvl", meaning: "schop" },
  { word: 'sieve', ipa: "sɪv", meaning: "zeef" },
  { word: 'signal (n/v)', ipa: "ˈsɪɡnl" },
  { word: 'simile', ipa: "ˈsɪmɪli" },
  { word: 'simultaneity', ipa: "ˈsɪmltəˈneɪəti", meaning: "gelijktijdigheid" },
  { word: 'simultaneous', ipa: "ˈsɪmlˈteɪmjəs" },
  { word: 'sinecure', ipa: "ˈsæmɪkjuə" },
  { word: 'singe', ipa: "ˈsɪndʒ", meaning: "(ver)schroeien" },
  { word: 'slander (n/v)', ipa: "ˈslɑːndə", meaning: "(be)lasteren" },
  { word: 'slaughter (n/v)', ipa: "ˈslɔːtə" },
  { word: 'sleigh', ipa: "sleɪ" },
  { word: 'slough', ipa: "slaʊ", meaning: "the Slough of Despond (moeras)" },
  { word: 'slovenly', ipa: "ˈslʌvnli", meaning: "untidy; slatternly" },
  { word: 'sluice', ipa: "sluːs", meaning: "spui" },
  { word: 'smooth (adj./v)', ipa: "smuːð" },
  { word: 'smoulder', ipa: "ˈsməʊldə", meaning: "smeulen" },
  { word: 'socialism', ipa: "ˈsəʊʃəlɪzm" },
  { word: 'sociology', ipa: "ˈsəʊsɪˈblɒdʒi" },
  { word: 'sojourn (n/v)', ipa: "ˈsɒdʒɜːn", meaning: "verblijf; verblijven" },
  { word: 'solace', ipa: "ˈsɒpləs" },
  { word: 'soldier', ipa: "ˈsəʊldʒə" },
  { word: 'solicitor', ipa: "ˈsəʊlɪsɪtə" },
  { word: 'soliloquy', ipa: "səˈlɪlɪkwi", meaning: "alleenspraak (toneel)" },
  { word: 'soothe', ipa: "suːð", meaning: "sussen" },
  { word: 'Sotheby\'s', ipa: "ˈsʌðəbɪz", meaning: "Londens veilinghuis" },
  { word: 'soup', ipa: "suːp" },
  { word: 'sour', ipa: "ˈsaʊə", meaning: "the milk has turned sour" },
  { word: 'Southwark', ipa: "ˈsʌðək" },
  { word: 'sovereign', ipa: "ˈsɒvrɪn" },
  { word: 'sow (n)', ipa: "saʊ", meaning: "female pig" },
  { word: 'sow (v)', ipa: "səʊ", meaning: "zaaien" },
  { word: 'Spaniard', ipa: "ˈspænjəd" },
  { word: 'spaniel', ipa: "ˈspænjəl" },
  { word: 'sparse(ly)', ipa: "spɑːs(li)", meaning: "sparsely populated" },
  { word: 'spear', ipa: "spɪə" },
  { word: 'species (sg/pl)', ipa: "ˈspiːsɪz", meaning: "the human species" },
  { word: 'specious', ipa: "ˈspiːʃəs", meaning: "schoonschijnend" },
  { word: 'spectator', ipa: "spekˈteɪtə" },
  { word: 'spinach', ipa: "ˈspɪnɪdʒ" },
  { word: 'sponge', ipa: "spʌndʒ", meaning: "spons" },
  { word: 'spontaneity', ipa: "ˈspɒntəˈneɪəti" },
  { word: 'spontaneous', ipa: "spɒnˈteɪmjəs" },
  { word: 'spread (n/v)', ipa: "spred" },
  { word: 'squalid', ipa: "ˈskwɒlɪd", meaning: "dirty, mean; poverty-stricken" },
  { word: 'squirrel', ipa: "ˈskwɪrəl", meaning: "eekhoorn" },
  { word: 'stalwart (n/adj.)', ipa: "ˈstɔːlwət", meaning: "party stalwarts" },
  { word: 'stamina', ipa: "ˈstæmɪnə", meaning: "uithoudingsvermogen" },
  { word: 'staunch', ipa: "stɔːntʃ", meaning: "trustworthy, loyal, firm" },
  { word: 'stealth(y)', ipa: "stelθ(i)" },
  { word: 'stingy', ipa: "ˈstɪndʒi", meaning: "gierig" },
  { word: 'stipend', ipa: "ˈstaɪpend" },
  { word: 'stirrup', ipa: "ˈstɪrəp" },
  { word: 'stomach', ipa: "ˈstʌmək" },
  { word: 'stood', ipa: "stʊd" },
  { word: 'strategic', ipa: "strəˈtiːdʒɪk" },
  { word: 'strategist', ipa: "ˈstrætədʒɪst" },
  { word: 'strophe', ipa: "ˈstrɒfi" },
  { word: 'studious', ipa: "ˈstjuːdɪəs" },
  { word: 'sublime', ipa: "səˈblaɪm" },
  { word: 'success', ipa: "səkˈses" },
  { word: 'suede', ipa: "sweɪd" },
  { word: 'suicide', ipa: "ˈsuːɪsaɪd" },
  { word: 'suit', ipa: "suːt" },
  { word: 'suite', ipa: "swiːt" },
  { word: 'superb', ipa: "suːˈpɜːb" },
  { word: 'supplement (n/adj.)', ipa: "ˈsʌplɪmənt" },
  { word: 'supplement (v)', ipa: "ˈsʌplɪment" },
  { word: 'surgeon', ipa: "ˈsɜːdʒən" },
  { word: 'surmise', ipa: "sɜːˈmaɪz", meaning: "to guess, conjecture" },
  { word: 'surprise', ipa: "səˈpraɪz" },
  { word: 'Susan', ipa: "ˈsuːzn" },
  { word: 'swamp', ipa: "swɒmp" },
  { word: 'swarthy', ipa: "ˈswɔːðɪ", meaning: "~ complexion (donkere gelaatskleur)" },
  { word: 'sweater', ipa: "ˈswetə" },
  { word: 'swollen', ipa: "ˈswəʊlən" },
  { word: 'sword', ipa: "sɔːd" },
  { word: 'synod', ipa: "ˈsɪnəd" },
  { word: 'syringe', ipa: "ˈsɪrɪndʒ", meaning: "(injectie)spuit(je)" },
  { word: 'tally', ipa: "ˈtæli", meaning: "to keep a tally (aantekening houden)" },
  { word: 'talk', ipa: "tɔːk" },
  { word: 'tangerine', ipa: "ˈtændʒəˈriːn", meaning: "mandarijntje" },
  { word: 'tarry', ipa: "ˈtæri", meaning: "aarzelen, dralen" },
  { word: 'tease', ipa: "tiːz" },
  { word: 'tedious', ipa: "ˈtiːdɪəs" },
  { word: 'television', ipa: "ˈtelɪvɪʒn" },
  { word: 'tempestuous', ipa: "temˈpestʃuəs" },
  { word: 'temporarily', ipa: "ˈtemprərəli" },
  { word: 'terrace', ipa: "ˈterəs", meaning: "terraced house (in \'n rij)" },
  { word: 'theatre', ipa: "ˈθɪətə" },
  { word: 'thermometer', ipa: "θəˈmɒmɪtə" },
  { word: 'though', ipa: "ðəʊ" },
  { word: 'thread', ipa: "θred" },
  { word: 'threat', ipa: "θret" },
  { word: 'threshold', ipa: "ˈθreʃhəʊld", meaning: "drempel" },
  { word: 'timber', ipa: "ˈtɪmbə", meaning: "timmerhout" },
  { word: 'toll', ipa: "təʊl", meaning: "a toll-gate; the death-toll" },
  { word: 'tomato', ipa: "təˈmɑːtəʊ" },
  { word: 'tomb', ipa: "tuːm" },
  { word: 'ton(nage)', ipa: "ˈtʌn(ɪdʒ)" },
  { word: 'tongue', ipa: "tʌŋ" },
  { word: 'tornado', ipa: "tɔːˈneɪdəʊ" },
  { word: 'tortoise', ipa: "ˈtɔːtəs", meaning: "(land)schildpad" },
  { word: 'tough', ipa: "tʌf" },
  { word: 'tow', ipa: "təʊ", meaning: "on tow (sleep)" },
  { word: 'towards', ipa: "təˈwɔːdz" },
  { word: 'trachea', ipa: "trəˈkiːə" },
  { word: 'trance', ipa: "trɑːns" },
  { word: 'transaction', ipa: "trænˈzækʃn" },
  { word: 'transistor', ipa: "trænˈzɪstə" },
  { word: 'transition', ipa: "trænˈzɪʃn" },
  { word: 'transitive', ipa: "ˈtrænsətɪv" },
  { word: 'transmit', ipa: "trænzˈmɪt" },
  { word: 'treachery', ipa: "ˈtretʃəri", meaning: "disloyalty; deceit" },
  { word: 'treason', ipa: "ˈtriːzn", meaning: "treachery to one\'s country" },
  { word: 'treasure', ipa: "ˈtreʒə" },
  { word: 'treble', ipa: "ˈtrebl" },
  { word: 'triangle', ipa: "ˈtraɪæŋɡl" },
  { word: 'tribunal', ipa: "traɪˈbjuːnl" },
  { word: 'triple', ipa: "trɪpl", meaning: "triple time: driekwartsmaat" },
  { word: 'trivial', ipa: "ˈtrɪvɪəl" },
  { word: 'trophy', ipa: "ˈtrəʊfi" },
  { word: 'trough', ipa: "trɒf", meaning: "trog" },
  { word: 'truth', ipa: "truːθ" },
  { word: 'tuition', ipa: "tjuːˈɪʃn" },
  { word: 'tumult', ipa: "ˈtjuːmʌlt" },
  { word: 'twopence', ipa: "ˈtʌpəns", meaning: "(before decimalisation)" },
  { word: 'Tyne and Wear', ipa: "ˈtaɪn ən ˈwɪə", meaning: "English county" },
  { word: 'typhoid', ipa: "ˈtaɪfɔɪd" },
  { word: 'tyranny', ipa: "ˈtɪrəni" },
  { word: 'uncouth', ipa: "ʌnˈkuːθ", meaning: "rough, uncultured" },
  { word: 'unrest', ipa: "ʌnˈrest", meaning: "political unrest" },
  { word: 'urine', ipa: "ˈjʊərɪn" },
  { word: 'usage', ipa: "ˈjuːsɪdʒ" },
  { word: 'used (adj.)', ipa: "juːst", meaning: "get used to sth." },
  { word: 'used (pp)', ipa: "juːzd", meaning: "pp of to use" },
  { word: 'used to', ipa: "ˈjuːstə", meaning: "he used to drink a lot" },
  { word: 'utensil', ipa: "juːˈtensl", meaning: "kitchen utensils" },
  { word: 'vaccine', ipa: "ˈvæksiːn" },
  { word: 'vaccination', ipa: "ˈvæksɪˈneɪʃən" },
  { word: 'vagrancy', ipa: "ˈveɪɡrənsi", meaning: "landloperi" },
  { word: 'vague', ipa: "veɪɡ" },
  { word: 'valiant', ipa: "ˈvæljənt", meaning: "brave" },
  { word: 'valise', ipa: "vəˈliːz" },
  { word: 'variable (adj./n)', ipa: "ˈveərɪəbl" },
  { word: 'variety', ipa: "vəˈraɪəti" },
  { word: 'vase', ipa: "vɑːz" },
  { word: 'Vaughan', ipa: "vɔːn" },
  { word: 'vengeance', ipa: "ˈvendʒəns", meaning: "wraak" },
  { word: 'venison', ipa: "ˈvenɪsn", meaning: "wildbraad" },
  { word: 'venom', ipa: "ˈvenəm", meaning: "venomous snakes" },
  { word: 'veranda', ipa: "vəˈrændə" },
  { word: 'veritable', ipa: "ˈverɪtəbl" },
  { word: 'veterinary', ipa: "ˈvetrɪnri", meaning: "a vet(erinary surgeon)" },
  { word: 'veto (n/v)', ipa: "ˈviːtəʊ" },
  { word: 'vice versa', ipa: "ˈvaɪsi ˈvɜːsə" },
  { word: 'vinegar', ipa: "ˈvɪnɪɡə", meaning: "azijn" },
  { word: 'vineyard', ipa: "ˈvɪnjəd" },
  { word: 'violet', ipa: "ˈvaɪələt" },
  { word: 'violin', ipa: "ˈvaɪəˈlɪn" },
  { word: 'violinist', ipa: "ˈvaɪəlɪnɪst" },
  { word: 'VIP', ipa: "ˈviː aɪ ˈpiː" },
  { word: 'viscera', ipa: "ˈvɪsərə", meaning: "ingewanden" },
  { word: 'viscount', ipa: "ˈvaɪkaʊnt" },
  { word: 'volcano', ipa: "vɒlˈkeməʊ" },
  { word: 'voluntary', ipa: "ˈvɒləntri" },
  { word: 'vow (n/v)', ipa: "vaʊ", meaning: "solemn promise" },
  { word: 'wainscotting', ipa: "ˈweɪmskətɪŋ", meaning: "lambrizering" },
  { word: 'waistcoat', ipa: "ˈweɪskəʊt", meaning: "vest (van driedelig pak)" },
  { word: 'wan', ipa: "wɒn", meaning: "bleek" },
  { word: 'war', ipa: "wɔː" },
  { word: 'warrant', ipa: "ˈwɒrənt" },
  { word: 'wasp', ipa: "wɒsp" },
  { word: 'water', ipa: "ˈwɔːtə" },
  { word: 'weasel', ipa: "ˈwiːzl", meaning: "wezel" },
  { word: 'Wednesday', ipa: "ˈwenzdi" },
  { word: 'weigh', ipa: "weɪ" },
  { word: 'weight (n/v/)', ipa: "weɪt" },
  { word: 'weird', ipa: "wɪəd", meaning: "uncanny, strange" },
  { word: 'wharf', ipa: "wɔːf", meaning: "kade (werf = shipyard)" },
  { word: 'where', ipa: "weə" },
  { word: 'whimsical', ipa: "ˈwɪmzəkl" },
  { word: 'wilderness', ipa: "ˈwɪldənɪs" },
  { word: 'Windsor', ipa: "ˈwɪnzə" },
  { word: 'with', ipa: "wɪð" },
  { word: 'wizard', ipa: "ˈwɪzəd", meaning: "magician" },
  { word: 'Wolsey', ipa: "ˈwʊlzi" },
  { word: 'won', ipa: "wʌn", meaning: "pt and pp of to win" },
  { word: 'wonder', ipa: "ˈwʌndə" },
  { word: 'worm', ipa: "wɜːm" },
  { word: 'wound (n)', ipa: "wuːnd" },
  { word: 'wound (v)', ipa: "waʊnd", meaning: "pt and pp of to wind" },
  { word: 'wrath', ipa: "rɒθ", meaning: "toorn" },
  { word: 'wreathe (v)', ipa: "riːð", meaning: "vlechten, kronkelen" },
  { word: 'wretched', ipa: "ˈretʃɪd" },
  { word: 'wrought', ipa: "rɔːt" },
  { word: 'xenophobe', ipa: "ˈzenəfəʊb", meaning: "person fearing foreigners" },
  { word: 'xerox (n/v)', ipa: "ˈzɪərɒks" },
  { word: 'yacht', ipa: "jɒt" },
  { word: 'yearn', ipa: "jɜːn", meaning: "long for with affection" },
  { word: 'yeoman', ipa: "ˈjəʊmən" },
  { word: 'yolk', ipa: "jəʊk", meaning: "the yolk of an egg" },
  { word: 'your', ipa: "jɔː" },
  { word: 'zeal', ipa: "ziːl", meaning: "enthusiasm" },
  { word: 'zealot', ipa: "ˈzelət", meaning: "fanatic" },
  { word: 'zealous', ipa: "ˈzeləs" },
  { word: 'zebra', ipa: "ˈzebrə", meaning: "a zebra crossing" },
  { word: 'zoology', ipa: "zəʊˈblɒdʒi" },

  // ── Added from card rules  { word: 'academic', ipa: "ˈækəˈdemɪk", generated: true },
  { word: 'adjourn', ipa: "əˈdʒɜːn", generated: true },
  { word: 'again', ipa: "əˈɡen, əˈɡeɪn", generated: true },
  { word: 'Alnwick', ipa: "ˈænɪk", generated: true },
  { word: 'analysis', ipa: "əˈnæləsɪs", generated: true },
  { word: 'anecdote', ipa: "ˈænəkdəʊt", generated: true, ipa_generated: true },
  { word: 'any', ipa: "ˈeni", generated: true, ipa_generated: true },
  { word: 'area', ipa: "ˈeəriə", generated: true },
  { word: 'Asia', ipa: "ˈeɪʃə", generated: true },
  { word: 'assuredly', ipa: "əˈʃɔːrɪdli", generated: true, ipa_generated: true },
  { word: 'ate', ipa: "et, eɪt", generated: true },
  { word: 'attention', ipa: "əˈtenʃən", generated: true, ipa_generated: true },
  { word: 'Austin', ipa: "ˈɒstɪn", generated: true },
  { word: 'Australia', ipa: "ɒˈstreɪliə", generated: true },
  { word: 'Austria', ipa: "ˈɒstriə", generated: true },
  { word: 'bags', ipa: "bæɡz", generated: true },
  { word: 'bare', ipa: "beə", generated: true },
  { word: 'barefoot', ipa: "ˈbeəfʊt", generated: true },
  { word: 'basis', ipa: "ˈbeɪsɪs", generated: true },
  { word: 'bath', ipa: "bɑːθ", generated: true },
  { word: 'bear', ipa: "beə", generated: true },
  { word: 'because', ipa: "bɪˈkɒz", generated: true },
  { word: 'Berkshire', ipa: "ˈbɑːkʃə", generated: true, ipa_generated: true },
  { word: 'Berwick', ipa: "ˈberɪk", generated: true },
  { word: 'blood', ipa: "blʌd", generated: true },
  { word: 'borough', ipa: "ˈbʌrə", generated: true },
  { word: 'bother', ipa: "ˈbɒðə", generated: true },
  { word: 'bottle', ipa: "ˈbɒtl̩", generated: true },
  { word: 'bottles', ipa: "ˈbɒtl̩z", generated: true },
  { word: 'break', ipa: "breɪk", generated: true, ipa_generated: true },
  { word: 'burial', ipa: "ˈberiəl", generated: true, ipa_generated: true },
  { word: 'bury', ipa: "ˈberi", generated: true, ipa_generated: true },
  { word: 'buses', ipa: "ˈbʌsɪz", generated: true },
  { word: 'business', ipa: "ˈbɪznɪs", generated: true },
  { word: 'busy', ipa: "ˈbɪzi", generated: true, ipa_generated: true },
  { word: 'button', ipa: "ˈbʌtn̩", generated: true },
  { word: 'calf', ipa: "kɑːf", generated: true },
  { word: 'called', ipa: "kɔːld", generated: true },
  { word: 'castle', ipa: "ˈkɑːsl̩", generated: true },
  { word: 'cattle', ipa: "ˈkætl̩", generated: true },
  { word: 'cauliflower', ipa: "ˈkɒliˌflaʊə", generated: true },
  { word: 'censure', ipa: "ˈsenʃə", generated: true, ipa_generated: true },
  { word: 'clerk', ipa: "klɑːk", generated: true, ipa_generated: true },
  { word: 'conflict', ipa: "ˈkɒnflɪkt", generated: true, ipa_generated: true },
  { word: 'Confucian', ipa: "kənˈfjuːʃən", generated: true, ipa_generated: true },
  { word: 'conjure', ipa: "ˈkʌndʒə", generated: true },
  { word: 'constable', ipa: "ˈkʌnstəbl", generated: true },
  { word: 'contest', ipa: "ˈkɒntest", generated: true },
  { word: 'cotton', ipa: "ˈkɒtn̩", generated: true },
  { word: 'Derby', ipa: "ˈdɑːbi", generated: true, ipa_generated: true },
  { word: 'Dulwich', ipa: "ˈdʌlɪdʒ", generated: true },
  { word: 'effect', ipa: "ɪˈfekt", generated: true, ipa_generated: true },
  { word: 'elf', ipa: "elf", generated: true },
  { word: 'England', ipa: "ˈɪŋɡlənd", generated: true, ipa_generated: true },
  { word: 'evasion', ipa: "ɪˈveɪʒən", generated: true, ipa_generated: true },
  { word: 'Evesham', ipa: "ˈiːvʃəm", generated: true },
  { word: 'excursion', ipa: "ɪkˈskɜːʃən", generated: true, ipa_generated: true },
  { word: 'Exmouth', ipa: "ˈeksmαʊθ", generated: true },
  { word: 'fission', ipa: "ˈfɪʃən", generated: true, ipa_generated: true },
  { word: 'fitted', ipa: "ˈfɪtɪd", generated: true },
  { word: 'flood', ipa: "flʌd", generated: true },
  { word: 'foot', ipa: "fʊt", generated: true },
  { word: 'garish', ipa: "ˈɡeərɪʃ", generated: true },
  { word: 'gather', ipa: "ˈɡæðə", generated: true, ipa_generated: true },
  { word: 'German', ipa: "ˈdʒɜːmən", generated: true, ipa_generated: true },
  { word: 'Gertrude', ipa: "ˈdʒɜːtruːd", generated: true, ipa_generated: true },
  { word: 'goes', ipa: "ɡəʊz", generated: true },
  { word: 'good', ipa: "ɡʊd", generated: true },
  { word: 'good-humouredly', ipa: "ˈɡʊd ˈhjuːmərdli", generated: true, ipa_generated: true },
  { word: 'great', ipa: "ɡreɪt", generated: true, ipa_generated: true },
  { word: 'Greenwich', ipa: "ˈɡrenɪdʒ", generated: true },
  { word: 'half', ipa: "hɑːf", generated: true },
  { word: 'harem', ipa: "ˈheərəm", generated: true },
  { word: 'heart', ipa: "hɑːt", generated: true, ipa_generated: true },
  { word: 'hearth', ipa: "hɑːθ", generated: true, ipa_generated: true },
  { word: 'helped', ipa: "helpt", generated: true },
  { word: 'higher', ipa: "ˈhaɪə", generated: true },
  { word: 'hire', ipa: "ˈhaɪə", generated: true },
  { word: 'hood', ipa: "hʊd", generated: true },
  { word: 'hour', ipa: "ˈaʊə", generated: true },
  { word: 'house', ipa: "haʊs", generated: true },
  { word: 'husband', ipa: "ˈhʌzbənd", generated: true, ipa_generated: true },
  { word: 'increase', ipa: "ˈɪŋkriːs", generated: true, ipa_generated: true },
  { word: 'Ipswich', ipa: "ˈɪpswɪtʃ", generated: true },
  { word: 'jam', ipa: "dʒæm", generated: true },
  { word: 'jet', ipa: "dʒet", generated: true },
  { word: 'Jones', ipa: "dʒəʊnz", generated: true },
  { word: 'journal', ipa: "ˈdʒɜːnəl", generated: true },
  { word: 'journey', ipa: "ˈdʒɜːni", generated: true },
  { word: 'Keswick', ipa: "ˈkezɪk", generated: true },
  { word: 'kisses', ipa: "ˈkɪsɪz", generated: true },
  { word: 'knife', ipa: "naɪf", generated: true },
  { word: 'knocked', ipa: "nɒkt", generated: true },
  { word: 'lascivious', ipa: "ləˈsɪviəs", generated: true, ipa_generated: true },
  { word: 'laurel', ipa: "ˈlɒrəl", generated: true },
  { word: 'leaf', ipa: "liːf", generated: true },
  { word: 'leather', ipa: "ˈleðə", generated: true, ipa_generated: true },
  { word: 'lesson', ipa: "ˈlesən", generated: true, ipa_generated: true },
  { word: 'Lewisham', ipa: "ˈluːɪʃəm", generated: true },
  { word: 'life', ipa: "laɪf", generated: true },
  { word: 'lips', ipa: "lɪps", generated: true },
  { word: 'listen', ipa: "ˈlɪsn̩", generated: true },
  { word: 'little', ipa: "ˈlɪtl̩", generated: true },
  { word: 'loaded', ipa: "ˈləʊdɪd", generated: true },
  { word: 'loaf', ipa: "ləʊf", generated: true },
  { word: 'loved', ipa: "lʌvd", generated: true },
  { word: 'many', ipa: "ˈmeni", generated: true, ipa_generated: true },
  { word: 'markedly', ipa: "ˈmɑːkɪdli", generated: true, ipa_generated: true },
  { word: 'market', ipa: "ˈmɑːkɪt", generated: true, ipa_generated: true },
  { word: 'Mary', ipa: "ˈmeəri", generated: true },
  { word: 'McLean', ipa: "məˈkleɪn", generated: true, ipa_generated: true },
  { word: 'measure', ipa: "ˈmeʒə", generated: true, ipa_generated: true },
  { word: 'mice', ipa: "maɪs", generated: true, ipa_generated: true },
  { word: 'mother', ipa: "ˈmʌðə", generated: true, ipa_generated: true },
  { word: 'mouth', ipa: "maʊθ", generated: true },
  { word: 'musician', ipa: "mjuːˈzɪʃən", generated: true, ipa_generated: true },
  { word: 'nation', ipa: "ˈneɪʃən", generated: true, ipa_generated: true },
  { word: 'nephew', ipa: "ˈnefjuː", generated: true, ipa_generated: true },
  { word: 'northern', ipa: "ˈnɔːðn", generated: true },
  { word: 'Norwich', ipa: "ˈnɒrɪdʒ", generated: true },
  { word: 'parent', ipa: "ˈpeərənt", generated: true },
  { word: 'path', ipa: "pɑːθ", generated: true },
  { word: 'pear', ipa: "peə", generated: true },
  { word: 'permit', ipa: "ˈpɜːmɪt", generated: true, ipa_generated: true },
  { word: 'pirate', ipa: "ˈpaɪərət", generated: true },
  { word: 'plaid', ipa: "plæd", generated: true, ipa_generated: true },
  { word: 'plait', ipa: "plæt", generated: true, ipa_generated: true },
  { word: 'popular', ipa: "ˈpɒpjʊlə", generated: true, ipa_generated: true },
  { word: 'possibility', ipa: "ˌpɒsəˈbɪləti", generated: true, ipa_generated: true },
  { word: 'pretty', ipa: "ˈprɪti", generated: true, ipa_generated: true },
  { word: 'prism', ipa: "ˈprɪzəm", generated: true, ipa_generated: true },
  { word: 'produce', ipa: "ˈprɒdjuːs", generated: true, ipa_generated: true },
  { word: 'protest', ipa: "ˈprəʊtest", generated: true, ipa_generated: true },
  { word: 'radio', ipa: "ˈreɪdiəʊ", generated: true, ipa_generated: true },
  { word: 'Reagan', ipa: "ˈreɪɡən", generated: true, ipa_generated: true },
  { word: 'reality', ipa: "rɪˈæləti", generated: true },
  { word: 'refuse', ipa: "ˈrefjuːs", generated: true, ipa_generated: true },
  { word: 'room', ipa: "ruːm, rʊm", generated: true },
  { word: 'roses', ipa: "ˈrəʊzɪz", generated: true, ipa_generated: true },
  { word: 'Sagittarius', ipa: "ˌsædʒɪˈteəriəs", generated: true },
  { word: 'said', ipa: "sed", generated: true, ipa_generated: true },
  { word: 'sausage', ipa: "ˈsɒsɪdʒ", generated: true },
  { word: 'says', ipa: "sez", generated: true },
  { word: 'scourge', ipa: "skɜːdʒ", generated: true },
  { word: 'scouring', ipa: "ˈskaʊərɪŋ", generated: true },
  { word: 'seizure', ipa: "ˈsiːʒə", generated: true, ipa_generated: true },
  { word: 'self', ipa: "self", generated: true },
  { word: 'sergeant', ipa: "ˈsɑːdʒənt", generated: true, ipa_generated: true },
  { word: 'seventeen', ipa: "ˌsevn̩ˈtiːn", generated: true },
  { word: 'share', ipa: "ʃeə", generated: true },
  { word: 'sheaf', ipa: "ʃiːf", generated: true },
  { word: 'shelf', ipa: "ʃelf", generated: true },
  { word: 'smokes', ipa: "sməʊks", generated: true },
  { word: 'snooker', ipa: "ˈsnuːkə", generated: true, ipa_generated: true },
  { word: 'solarium', ipa: "səˈleəriəm", generated: true },
  { word: 'southern', ipa: "ˈsʌðn", generated: true },
  { word: 'spook', ipa: "spuːk", generated: true, ipa_generated: true },
  { word: 'star', ipa: "stɑː", generated: true },
  { word: 'starring', ipa: "ˈstɑːrɪŋ", generated: true },
  { word: 'steak', ipa: "steɪk", generated: true, ipa_generated: true },
  { word: 'Stephen', ipa: "ˈstiːvən", generated: true, ipa_generated: true },
  { word: 'swear', ipa: "sweə", generated: true },
  { word: 'tear', ipa: "teə", generated: true },
  { word: 'tension', ipa: "ˈtenʃən", generated: true, ipa_generated: true },
  { word: 'Thames', ipa: "temz", generated: true, ipa_generated: true },
  { word: 'thief', ipa: "θiːf", generated: true },
  { word: 'thistle', ipa: "ˈθɪsl̩", generated: true, ipa_generated: true },
  { word: 'thorough', ipa: "ˈθʌrə", generated: true },
  { word: 'usual', ipa: "ˈjuːʒuəl", generated: true, ipa_generated: true },
  { word: 'variable', ipa: "ˈveəriəbl", generated: true },
  { word: 'various', ipa: "ˈveəriəs", generated: true },
  { word: 'vary', ipa: "ˈveəri", generated: true },
  { word: 'Vauxhall', ipa: "ˈvɒksɔːl", generated: true },
  { word: 'vegetarian', ipa: "ˌvedʒɪˈteəriən", generated: true },
  { word: 'vision', ipa: "ˈvɪʒən", generated: true, ipa_generated: true },
  { word: 'wear', ipa: "weə", generated: true },
  { word: 'wife', ipa: "waɪf", generated: true },
  { word: 'wisdom', ipa: "ˈwɪzdəm", generated: true, ipa_generated: true },
  { word: 'wolf', ipa: "wʊlf", generated: true },
  { word: 'women', ipa: "ˈwɪmɪn", generated: true },
  { word: 'wood', ipa: "wʊd", generated: true },
  { word: 'wool', ipa: "wʊl", generated: true },
  { word: 'worry', ipa: "ˈwʌri", generated: true },
  { word: 'Yeats', ipa: "jeɪts", generated: true, ipa_generated: true },
  { word: 'youth', ipa: "juːθ", generated: true },

  // ── Possessives from card rules ──────────────────────────────────────────


  // ── Derived forms (plurals, irregular) ─────────────────────────────────────
  { word: 'analyses', ipa: "əˈnæləsiːz", generated: true },
  { word: 'bases', ipa: "ˈbeɪsiːz", generated: true },
  { word: 'baths', ipa: "bɑːðz", generated: true },
  { word: 'calves', ipa: "kɑːvz", generated: true, ipa_generated: true },
  { word: 'elves', ipa: "elvz", generated: true, ipa_generated: true },
  { word: 'halves', ipa: "hɑːvz", generated: true, ipa_generated: true },
  { word: 'houses', ipa: "ˈhaʊzɪz", generated: true },
  { word: 'knives', ipa: "naɪvz", generated: true, ipa_generated: true },
  { word: 'leaves', ipa: "liːvz", generated: true, ipa_generated: true },
  { word: 'lives', ipa: "laɪvz", generated: true, ipa_generated: true },
  { word: 'loaves', ipa: "ləʊvz", generated: true, ipa_generated: true },
  { word: 'mouths', ipa: "maʊðz", generated: true },
  { word: 'paths', ipa: "pɑːðz", generated: true },
  { word: 'selves', ipa: "selvz", generated: true, ipa_generated: true },
  { word: 'sheaves', ipa: "ʃiːvz", generated: true, ipa_generated: true },
  { word: 'shelves', ipa: "ʃelvz", generated: true, ipa_generated: true },
  { word: 'thieves', ipa: "θiːvz", generated: true, ipa_generated: true },
  { word: 'wives', ipa: "waɪvz", generated: true, ipa_generated: true },
  { word: 'wolves', ipa: "wʊlvz", generated: true, ipa_generated: true },
  { word: 'youths', ipa: "juːðz", generated: true },

  // ── From book pages 22–29 (marked for review) ──────────────────────────────
  { word: 'about', ipa: "əˈbaʊt", generated: true },
  { word: 'assured', ipa: "əˈʃɔːd", generated: true },
  { word: 'bagged', ipa: "bæɡd", generated: true },
  { word: 'balls', ipa: "bɔːlz", generated: true },
  { word: 'ban', ipa: "bæn", generated: true },
  { word: 'band', ipa: "bænd", generated: true },
  { word: 'bars', ipa: "bɑːz", generated: true },
  { word: 'bean', ipa: "biːn", generated: true },
  { word: 'beer', ipa: "bɪə", generated: true },
  { word: 'bone', ipa: "bəʊn", generated: true },
  { word: 'books', ipa: "bʊks", generated: true },
  { word: 'born', ipa: "bɔːn", generated: true },
  { word: 'boy', ipa: "bɔɪ", generated: true },
  { word: 'breathed', ipa: "briːðd", generated: true },
  { word: 'burn', ipa: "bɜːn", generated: true },
  { word: 'bushes', ipa: "ˈbʊʃɪz", generated: true },
  { word: 'calm', ipa: "kɑːm", generated: true },
  { word: 'char', ipa: "tʃɑː", generated: true },
  { word: 'combed', ipa: "kəʊmd", generated: true },
  { word: 'coughs', ipa: "kɒfs", generated: true },
  { word: 'dawn', ipa: "dɔːn", generated: true },
  { word: 'diagnosed', ipa: "ˌdaɪəɡˈnəʊzd", generated: true },
  { word: 'dock', ipa: "dɒk", generated: true },
  { word: 'far', ipa: "fɑː", generated: true },
  { word: 'feel', ipa: "fiːl", generated: true },
  { word: 'fine', ipa: "faɪn", generated: true },
  { word: 'fond', ipa: "fɒnd", generated: true },
  { word: 'hall', ipa: "hɔːl", generated: true },
  { word: 'hare', ipa: "heə", generated: true },
  { word: 'jar', ipa: "dʒɑː", generated: true },
  { word: 'jilted', ipa: "ˈdʒɪltɪd", generated: true },
  { word: 'judges', ipa: "ˈdʒʌdʒɪz", generated: true },
  { word: 'kings', ipa: "kɪŋz", generated: true },
  { word: 'leashed', ipa: "liːʃt", generated: true },
  { word: 'lights', ipa: "laɪts", generated: true },
  { word: 'lip', ipa: "lɪp", generated: true },
  { word: 'longed', ipa: "lɒŋd", generated: true },
  { word: 'loves', ipa: "lʌvz", generated: true },
  { word: 'map', ipa: "mæp", generated: true },
  { word: 'marked', ipa: "mɑːkt", generated: true },
  { word: 'mined', ipa: "maɪnd", generated: true },
  { word: 'moths', ipa: "mɒθs", generated: true },
  { word: 'nail', ipa: "neɪl", generated: true },
  { word: 'pang', ipa: "pæŋ", generated: true },
  { word: 'pelican', ipa: "ˈpelɪkən", generated: true },
  { word: 'pens', ipa: "penz", generated: true },
  { word: 'pronounced', ipa: "prəˈnaʊnst", generated: true },
  { word: 'pull', ipa: "pʊl", generated: true },
  { word: 'rip', ipa: "rɪp", generated: true },
  { word: 'shell', ipa: "ʃel", generated: true },
  { word: 'sink', ipa: "sɪŋk", generated: true },
  { word: 'snarled', ipa: "snɑːld", generated: true },
  { word: 'spoon', ipa: "spuːn", generated: true },
  { word: 'stabbed', ipa: "stæbd", generated: true },
  { word: 'staged', ipa: "steɪdʒd", generated: true },
  { word: 'storms', ipa: "stɔːmz", generated: true },
  { word: 'stuffed', ipa: "stʌft", generated: true },
  { word: 'tabs', ipa: "tæbz", generated: true },
  { word: 'think', ipa: "θɪŋk", generated: true },
  { word: 'tin', ipa: "tɪn", generated: true },
  { word: 'tour', ipa: "tʊə", generated: true },
  { word: 'trays', ipa: "treɪz", generated: true },
  { word: 'veal', ipa: "viːl", generated: true },
  { word: 'yap', ipa: "jæp", generated: true },
  { word: 'zinc', ipa: "zɪŋk", generated: true },

  // ── From Chapter 3: Word Stress (p40–49, marked for review) ───────────────
  { word: 'absent', ipa: "ˈæbsənt", generated: true },
  { word: 'admirable', ipa: "ˈædmrəbl", generated: true },
  { word: 'admire', ipa: "ədˈmaɪə", generated: true },
  { word: 'alligator', ipa: "ˈælɪɡeɪtə", generated: true },
  { word: 'applicable', ipa: "ˈæplɪkəbl", generated: true },
  { word: 'arbitration', ipa: "ˌɑːbəˈtreɪʃn", generated: true },
  { word: 'bidder', ipa: "ˈbɪdə", generated: true },
  { word: 'canteen', ipa: "kænˈtiːn", generated: true },
  { word: 'cavity', ipa: "ˈkævəti", generated: true },
  { word: 'city', ipa: "ˈsɪti", generated: true },
  { word: 'comparable', ipa: "ˈkɒmprəbl", generated: true },
  { word: 'compare', ipa: "kəmˈpeə", generated: true },
  { word: 'consider', ipa: "kənˈsɪdə", generated: true },
  { word: 'constipation', ipa: "ˌkɒnstəˈpeɪʃn", generated: true },
  { word: 'crisis', ipa: "ˈkraɪsɪs", generated: true },
  { word: 'December', ipa: "dɪˈsembə", generated: true },
  { word: 'demonstrable', ipa: "dɪˈmɒnstrəbl", generated: true },
  { word: 'desirable', ipa: "dɪˈzaɪərəbl", generated: true },
  { word: 'desire', ipa: "dɪˈzaɪə", generated: true },
  { word: 'despicable', ipa: "dɪˈspɪkəbl", generated: true },
  { word: 'development', ipa: "dɪˈveləpmənt", generated: true },
  { word: 'difficult', ipa: "ˈdɪfɪkəlt", generated: true },
  { word: 'dispute', ipa: "dɪˈspjuːt", generated: true },
  { word: 'entertain', ipa: "ˌentəˈteɪn", generated: true },
  { word: 'eradicate', ipa: "ɪˈrædɪkeɪt", generated: true },
  { word: 'exhaust', ipa: "ɪɡˈzɔːst", generated: true },
  { word: 'exile', ipa: "ˈeksaɪl", generated: true },
  { word: 'formidable', ipa: "ˈfɔːmɪdəbl", generated: true },
  { word: 'hospitable', ipa: "ˈhɒspɪtəbl", generated: true },
  { word: 'impenetrable', ipa: "ɪmˈpenətrəbl", generated: true },
  { word: 'incubation', ipa: "ˌɪŋkjuˈbeɪʃn", generated: true },
  { word: 'ineradicable', ipa: "ˌɪnɪˈrædɪkəbl", generated: true },
  { word: 'inexhaustible', ipa: "ˌɪnɪɡˈzɔːstəbl", generated: true },
  { word: 'inexplicable', ipa: "ɪnˈeksplɪkəbl", generated: true },
  { word: 'inextricable', ipa: "ɪnˈekstrɪkəbl", generated: true },
  { word: 'insult', ipa: "ˈɪnsʌlt", generated: true },
  { word: 'interview', ipa: "ˈɪntəvjuː", generated: true },
  { word: 'irrefutable', ipa: "ɪˈrefjʊtəbl", generated: true },
  { word: 'lament', ipa: "ləˈment", generated: true },
  { word: 'lamentable', ipa: "ˈlæməntəbl", generated: true },
  { word: 'later', ipa: "ˈleɪtə", generated: true },
  { word: 'menace', ipa: "ˈmenəs", generated: true },
  { word: 'navigable', ipa: "ˈnævɪɡəbl", generated: true },
  { word: 'navigate', ipa: "ˈnævɪɡeɪt", generated: true },
  { word: 'negligible', ipa: "ˈneɡlɪdʒəbl", generated: true },
  { word: 'obtain', ipa: "əbˈteɪn", generated: true },
  { word: 'original', ipa: "əˈrɪdʒɪnəl", generated: true },
  { word: 'originality', ipa: "əˌrɪdʒɪˈnæləti", generated: true },
  { word: 'penetrate', ipa: "ˈpenɪtreɪt", generated: true },
  { word: 'platoon', ipa: "pləˈtuːn", generated: true },
  { word: 'political', ipa: "pəˈlɪtɪkl", generated: true },
  { word: 'pontoon', ipa: "pɒnˈtuːn", generated: true },
  { word: 'prefer', ipa: "prɪˈfɜː", generated: true },
  { word: 'preferable', ipa: "ˈprefərəbl", generated: true },
  { word: 'process', ipa: "ˈprəʊses", generated: true },
  { word: 'processable', ipa: "ˈprəʊsesəbl", generated: true },
  { word: 'purchase', ipa: "ˈpɜːtʃəs", generated: true },
  { word: 'repair', ipa: "rɪˈpeə", generated: true },
  { word: 'reparable', ipa: "ˈrepərəbl", generated: true },
  { word: 'reprimand', ipa: "ˈreprɪmɑːnd", generated: true },
  { word: 'reputable', ipa: "ˈrepjʊtəbl", generated: true },
  { word: 'repute', ipa: "rɪˈpjuːt", generated: true },
  { word: 'resort', ipa: "rɪˈzɔːt", generated: true },
  { word: 'revocable', ipa: "ˈrevəkəbl", generated: true },
  { word: 'revoke', ipa: "rɪˈvəʊk", generated: true },
  { word: 'sane', ipa: "seɪn", generated: true },
  { word: 'sanity', ipa: "ˈsænɪti", generated: true },
  { word: 'September', ipa: "sepˈtembə", generated: true },
  { word: 'serene', ipa: "səˈriːn", generated: true },
  { word: 'serenity', ipa: "səˈrenɪti", generated: true },
  { word: 'shallot', ipa: "ʃəˈlɒt", generated: true },
  { word: 'sonority', ipa: "səˈnɒrəti", generated: true },
  { word: 'stupid', ipa: "ˈstjuːpɪd", generated: true },
  { word: 'submerge', ipa: "səbˈmɜːdʒ", generated: true },
  { word: 'syllable', ipa: "ˈsɪləbl", generated: true },
  { word: 'Tequila', ipa: "təˈkiːlə", generated: true },
  { word: 'tycoon', ipa: "taɪˈkuːn", generated: true },
  { word: 'viscosity', ipa: "vɪˈskɒsɪti", generated: true },
  { word: 'viscous', ipa: "ˈvɪskəs", generated: true },
  { word: 'volunteer', ipa: "ˌvɒlənˈtɪə", generated: true },
  { word: 'voodoo', ipa: "ˈvuːduː", generated: true },
  { word: 'vulgarity', ipa: "vʌlˈɡærəti", generated: true },

  // ── Homograph pairs from Chapter 3 (p44–47, marked for review) ────────────
  { word: 'absent (v)', ipa: "əbˈsent", meaning: 'to absent oneself', generated: true },
  { word: 'abstract', ipa: "ˈæbstrækt", meaning: 'resumé; abstract painting', generated: true },
  { word: 'abstract (v)', ipa: "əbˈstrækt", meaning: 'to abstract', generated: true },
  { word: 'accent', ipa: "ˈæksnt", meaning: 'accent', generated: true },
  { word: 'accent (v)', ipa: "ækˈsent", meaning: 'to accent a syllable', generated: true },
  { word: 'addict', ipa: "ˈædɪkt", meaning: 'verslaafde, junkie', generated: true },
  { word: 'addict (v)', ipa: "əˈdɪkt", meaning: 'to become addicted', generated: true },
  { word: 'affix', ipa: "ˈæfɪks", meaning: 'affix (grammar)', generated: true },
  { word: 'affix (v)', ipa: "əˈfɪks", meaning: 'to affix', generated: true },
  { word: 'ally', ipa: "ˈælaɪ", meaning: 'bondgenoot', generated: true },
  { word: 'ally (v)', ipa: "əˈlaɪ", meaning: 'to ally', generated: true },
  { word: 'attribute', ipa: "ˈætrɪbjuːt", meaning: 'eigenschap, kenmerk', generated: true },
  { word: 'attribute (v)', ipa: "əˈtrɪbjuːt", meaning: 'to attribute', generated: true },
  { word: 'combat', ipa: "ˈkɒmbæt", meaning: 'gevecht/vechten', generated: true },
  { word: 'combine', ipa: "ˈkɒmbaɪn", meaning: 'combine harvester', generated: true },
  { word: 'combine (v)', ipa: "kəmˈbaɪn", meaning: 'to combine', generated: true },
  { word: 'comment', ipa: "ˈkɒment", meaning: 'commentaar/commentaar geven', generated: true },
  { word: 'compound', ipa: "ˈkɒmpaʊnd", meaning: 'samenstelling; samengesteld', generated: true },
  { word: 'compound (v)', ipa: "kəmˈpaʊnd", meaning: 'to compound', generated: true },
  { word: 'compress', ipa: "ˈkɒmpres", meaning: 'kompres', generated: true },
  { word: 'compress (v)', ipa: "kəmˈpres", meaning: 'to compress', generated: true },
  { word: 'concert', ipa: "ˈkɒnsət", meaning: 'concert', generated: true },
  { word: 'concert (v)', ipa: "kənˈsɜːt", meaning: 'concerted action', generated: true },
  { word: 'conduct', ipa: "ˈkɒndʌkt", meaning: 'gedrag', generated: true },
  { word: 'conduct (v)', ipa: "kənˈdʌkt", meaning: 'to conduct an orchestra', generated: true },
  { word: 'conflict (v)', ipa: "kənˈflɪkt", meaning: 'to conflict', generated: true },
  { word: 'consort', ipa: "ˈkɒnsɔːt", meaning: 'Prince Consort', generated: true },
  { word: 'consort (v)', ipa: "kənˈsɔːt", meaning: 'to consort with criminals', generated: true },
  { word: 'contest (v)', ipa: "kənˈtest", meaning: 'to contest an election', generated: true },
  { word: 'contract', ipa: "ˈkɒntrækt", meaning: 'contract', generated: true },
  { word: 'contract (v)', ipa: "kənˈtrækt", meaning: 'to contract', generated: true },
  { word: 'contrast', ipa: "ˈkɒntrɑːst", meaning: 'contrast', generated: true },
  { word: 'contrast (v)', ipa: "kənˈtrɑːst", meaning: 'contrasting colours', generated: true },
  { word: 'converse', ipa: "ˈkɒnvɜːs", meaning: 'tegenovergestelde', generated: true },
  { word: 'converse (v)', ipa: "kənˈvɜːs", meaning: 'to converse', generated: true },
  { word: 'convert', ipa: "ˈkɒnvɜːt", meaning: 'bekeerling', generated: true },
  { word: 'convert (v)', ipa: "kənˈvɜːt", meaning: 'to convert', generated: true },
  { word: 'convict', ipa: "ˈkɒnvɪkt", meaning: 'veroordeelde', generated: true },
  { word: 'convict (v)', ipa: "kənˈvɪkt", meaning: 'to convict', generated: true },
  { word: 'debate', ipa: "dɪˈbeɪt", meaning: 'debat/debatteren', generated: true },
  { word: 'decrease', ipa: "ˈdiːkriːs", meaning: 'afname', generated: true },
  { word: 'decrease (v)', ipa: "dɪˈkriːs", meaning: 'prices have decreased', generated: true },
  { word: 'defect', ipa: "ˈdiːfekt", meaning: 'gebrek, defect', generated: true },
  { word: 'defect (v)', ipa: "dɪˈfekt", meaning: 'to defect to the enemy', generated: true },
  { word: 'desert', ipa: "ˈdezət", meaning: 'woestijn', generated: true },
  { word: 'desert (v)', ipa: "dɪˈzɜːt", meaning: 'to desert', generated: true },
  { word: 'digest', ipa: "ˈdaɪdʒest", meaning: 'samenvatting', generated: true },
  { word: 'digest (v)', ipa: "dɪˈdʒest", meaning: 'to digest food', generated: true },
  { word: 'discount', ipa: "ˈdɪskaʊnt", meaning: 'korting', generated: true },
  { word: 'discount (v)', ipa: "dɪsˈkaʊnt", meaning: 'to discount', generated: true },
  { word: 'disgrace', ipa: "dɪsˈɡreɪs", meaning: 'schande/te schande maken', generated: true },
  { word: 'disguise', ipa: "dɪsˈɡaɪz", meaning: 'vermomming/vermommen', generated: true },
  { word: 'escort', ipa: "ˈeskɔːt", meaning: 'escorte', generated: true },
  { word: 'escort (v)', ipa: "ɪˈskɔːt", meaning: 'to escort', generated: true },
  { word: 'excise', ipa: "ˈeksaɪz", meaning: 'accijns', generated: true },
  { word: 'excise (v)', ipa: "ekˈsaɪz", meaning: 'to excise', generated: true },
  { word: 'export', ipa: "ˈekspɔːt", meaning: 'export', generated: true },
  { word: 'export (v)', ipa: "ɪkˈspɔːt", meaning: 'to export', generated: true },
  { word: 'extract', ipa: "ˈekstrækt", meaning: 'extract, excerpt', generated: true },
  { word: 'extract (v)', ipa: "ɪkˈstrækt", meaning: 'to extract a tooth', generated: true },
  { word: 'frequent', ipa: "ˈfriːkwənt", meaning: 'frequent', generated: true },
  { word: 'frequent (v)', ipa: "frɪˈkwent", meaning: 'to frequent a place', generated: true },
  { word: 'import', ipa: "ˈɪmpɔːt", meaning: 'import', generated: true },
  { word: 'import (v)', ipa: "ɪmˈpɔːt", meaning: 'to import raw materials', generated: true },
  { word: 'incense (v)', ipa: "ɪnˈsens", meaning: 'to incense (enrage)', generated: true },
  { word: 'increase (v)', ipa: "ɪŋˈkriːs", meaning: 'to increase wages', generated: true },
  { word: 'insult (v)', ipa: "ɪnˈsʌlt", meaning: 'to insult', generated: true },
  { word: 'interchange', ipa: "ˈɪntətʃeɪndʒ", meaning: 'railway interchange', generated: true },
  { word: 'interchange (v)', ipa: "ˌɪntəˈtʃeɪndʒ", meaning: 'to interchange', generated: true },
  { word: 'object', ipa: "ˈɒbdʒɪkt", meaning: 'object, voorwerp', generated: true },
  { word: 'object (v)', ipa: "əbˈdʒekt", meaning: 'to object to something', generated: true },
  { word: 'overhaul', ipa: "ˈəʊvəhɔːl", meaning: 'revisie van motor', generated: true },
  { word: 'overhaul (v)', ipa: "ˌəʊvəˈhɔːl", meaning: 'to overhaul', generated: true },
  { word: 'perfect', ipa: "ˈpɜːfɪkt", meaning: 'perfect, nobody\\'s ~', generated: true },
  { word: 'perfect (v)', ipa: "pəˈfekt", meaning: 'to perfect one\\'s English', generated: true },
  { word: 'perfume', ipa: "ˈpɜːfjuːm", meaning: 'parfum', generated: true },
  { word: 'perfume (v)', ipa: "pəˈfjuːm", meaning: 'to perfume', generated: true },
  { word: 'permit (v)', ipa: "pəˈmɪt", meaning: 'weather permitting', generated: true },
  { word: 'present', ipa: "ˈpreznt", meaning: 'cadeau; aanwezig', generated: true },
  { word: 'present (v)', ipa: "prɪˈzent", meaning: 'to present', generated: true },
  { word: 'produce (v)', ipa: "prəˈdjuːs", meaning: 'to produce', generated: true },
  { word: 'progress', ipa: "ˈprəʊɡres", meaning: 'vooruitgang', generated: true },
  { word: 'progress (v)', ipa: "prəˈɡres", meaning: 'we\\'re progressing slowly', generated: true },
  { word: 'project', ipa: "ˈprɒdʒekt", meaning: 'project', generated: true },
  { word: 'project (v)', ipa: "prəˈdʒekt", meaning: 'to project a slide', generated: true },
  { word: 'prospect', ipa: "ˈprɒspekt", meaning: 'vooruitzicht', generated: true },
  { word: 'prospect (v)', ipa: "prəˈspekt", meaning: 'to prospect for gold', generated: true },
  { word: 'protest (v)', ipa: "prəˈtest", meaning: 'to protest', generated: true },
  { word: 'rebel', ipa: "ˈrebl", meaning: 'rebel', generated: true },
  { word: 'rebel (v)', ipa: "rɪˈbel", meaning: 'to rebel against authority', generated: true },
  { word: 'record', ipa: "ˈrekɔːd", meaning: 'record; grammofoonplaat', generated: true },
  { word: 'record (v)', ipa: "rɪˈkɔːd", meaning: 'to record music', generated: true },
  { word: 'refuse (v)', ipa: "rɪˈfjuːz", meaning: 'to refuse', generated: true },
  { word: 'segment', ipa: "ˈseɡmənt", meaning: 'segment', generated: true },
  { word: 'segment (v)', ipa: "seɡˈment", meaning: 'to segment an orange', generated: true },
  { word: 'subject', ipa: "ˈsʌbdʒɪkt", meaning: 'onderwerp; vak', generated: true },
  { word: 'subject (v)', ipa: "səbˈdʒekt", meaning: 'to subject to discipline', generated: true },
  { word: 'survey', ipa: "ˈsɜːveɪ", meaning: 'overzicht', generated: true },
  { word: 'survey (v)', ipa: "səˈveɪ", meaning: 'to survey the field', generated: true },
  { word: 'suspect', ipa: "ˈsʌspekt", meaning: 'verdachte', generated: true },
  { word: 'suspect (v)', ipa: "səˈspekt", meaning: 'to suspect', generated: true },
  { word: 'torment', ipa: "ˈtɔːment", meaning: 'marteling', generated: true },
  { word: 'torment (v)', ipa: "tɔːˈment", meaning: 'to torment', generated: true },
  { word: 'transfer', ipa: "ˈtrænsfɜː", meaning: 'transfer', generated: true },
  { word: 'transfer (v)', ipa: "trænsˈfɜː", meaning: 'to transfer a footballer', generated: true },
  { word: 'transport', ipa: "ˈtrænspɔːt", meaning: 'vervoer', generated: true },
  { word: 'transport (v)', ipa: "trænˈspɔːt", meaning: 'to transport passengers', generated: true },
